import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*)<\/script>/)?.[1];
const scoring=JSON.parse(readFileSync(new URL('../src/scoring.json',import.meta.url),'utf8'));
assert.ok(script,'index.html contains an inline application script');
assert.doesNotThrow(()=>new Function(script),'application JavaScript parses');
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);
assert.equal(new Set(ids).size,ids.length,'HTML ids are unique');
for(const id of ['hardestGrade','bountySelect','activityNote','activityDate','identityMember','newParticipantName','proxyMember','endpoint','challengeStart','tripDate','groupGoalInput'])assert.match(html,new RegExp(`<label[^>]+for="${id}"`),`${id} has an associated label`);
for(const tab of ['you','record','crew']){
  assert.match(html,new RegExp(`data-panel="${tab}"`),`${tab} panel exists`);
  assert.match(html,new RegExp(`data-tab="${tab}"`),`${tab} navigation exists`);
}
assert.match(html,/class="bottom-nav"[^>]+aria-label="Primary"/,'bottom navigation is named');
assert.match(html,/id="recordMeter"[^>]+aria-label=/,'record preview meter is accessible');
assert.match(html,/id="syncDiagnostics"[^>]+role="status"[^>]+aria-live="polite"/,'persistent sync diagnostics are announced');
assert.match(html,/id="toast"[^>]+role="status"[^>]+aria-live="polite"/,'toast is announced');
for(const title of ['identityTitle','proxyTitle','setupTitle'])assert.match(html,new RegExp(`role="dialog"[^>]+aria-modal="true"[^>]+aria-labelledby="${title}"`),`${title} dialog is named`);
assert.match(html,/aria-label="Close identity picker"/);
assert.match(html,/aria-label="Close person picker"/);
assert.match(html,/aria-label="Close shared setup"/);
assert.deepEqual(Object.keys(scoring.categories),['climb','exercise','mobility'],'three categories are configured');
assert.equal(scoring.balancedDayBonus,2,'balanced-day bonus is configured');
assert.equal(scoring.weeklyBountyCap,6,'weekly bounty cap is configured');
assert.ok(Array.isArray(scoring.bounties)&&scoring.bounties.length>=6,'a bounty catalog is present');
assert.ok(scoring.bounties.every(b=>typeof b.id==='string'&&b.id&&typeof b.title==='string'&&b.title&&typeof b.description==='string'&&b.description&&Number.isInteger(b.points)&&b.points>=1&&b.points<=3&&['climb','exercise','mobility'].includes(b.category)),'each bounty has a name, description, integer 1-3 points, and a category');
assert.equal(new Set(scoring.bounties.map(b=>b.id)).size,scoring.bounties.length,'bounty ids are unique across the catalog');
for(const cat of Object.keys(scoring.categories))assert.ok(scoring.bounties.some(b=>b.category===cat),`the ${cat} bounty pool is not empty`);
assert.deepEqual(scoring.grades,['V0','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17']);
const sharedConfig=(script.match(/const GRADES=SCORING\.grades,CATEGORIES=Object\.keys\(SCORING\.categories\)/g)||[]).length;
assert.ok(sharedConfig>=2,'browser and Apps Script both read the shared scoring config');
assert.doesNotMatch(html,/Hard mode|Super hard mode|pull-up mode|Record send pyramid|Balanced week bonus/i,'removed pull-up-mode and legacy features are absent from the UI');
assert.match(script,/Saved to the Sheet, but refresh failed\. Do not retry/,'confirmed saves are distinguished from refresh failures');
assert.match(html,/Climbing[\s\S]*Exercise[\s\S]*Mobility/,'the three categories appear in the record picker');
assert.match(html,/Today's bounties/,'the rotating bounty card is present');
assert.match(html,/data-panel="you"[\s\S]*id="bountyCapHint"[\s\S]*id="todayBounties"/,'the weekly bounty-cap progress hint sits in the bounty card head on the You panel');
assert.match(html,/id="bountyHunter"/,'the Bounty Hunter slot is present');
assert.match(html,/id="goalPace"[^>]*role="status"[^>]*aria-live="polite"/,'the goal pace indicator is announced');
assert.match(html,/data-panel="crew"[\s\S]*id="goalPace"[\s\S]*?id="goalProjection"[^>]*role="status"[^>]*aria-live="polite"/,'the goal projection line follows the pace line in the crew panel and is announced');
assert.match(html,/id="youDailyMax"/,'the daily max is rendered from the scoring config');
assert.match(html,/data-panel="you"[\s\S]*id="youBreakdown"[\s\S]*data-panel="record"/,'the per-category breakdown card lives inside the You panel');
assert.match(html,/data-panel="you"[\s\S]*class="stat-grid"[\s\S]*id="youTotal"[\s\S]*id="youRank"[\s\S]*id="youStreak"[\s\S]*id="youBestStreak"[\s\S]*data-panel="record"/,'the current and best streak stat cards join the stat grid on the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="youBreakdown"[\s\S]*id="gradePyramid"[\s\S]*id="bountyCapHint"/,'the grade pyramid card sits between the category breakdown and the bounty card on the You panel');
assert.match(html,/id="gradePyramid"[^>]*role="img"[^>]*aria-label=/,'the grade pyramid is announced as a graphic');
assert.match(html,/data-panel="you"[\s\S]*id="gradePyramidCard"[\s\S]*id="heatmapCard"[\s\S]*id="bountyCapHint"/,'the daily activity heatmap card sits after the grade pyramid on the You panel');
assert.match(html,/id="youHeatmap"[^>]*role="img"[^>]*aria-label=/,'the daily activity heatmap is announced as a graphic');
assert.match(html,/data-panel="crew"[\s\S]*id="leaderToggle"[\s\S]*id="leaderRows"/,'the leaderboard view toggle lives inside the crew panel');
assert.match(html,/id="leaderWeekBtn"[^>]*type="button"[^>]*aria-pressed=/,'the Weekly toggle is a real button with aria-pressed');
assert.match(html,/id="leaderOverallBtn"[^>]*type="button"[^>]*aria-pressed=/,'the Overall toggle is a real button with aria-pressed');
assert.equal((html.match(/<table>/g)||[]).length,1,'all crew share one leaderboard');
assert.match(html,/env\(safe-area-inset-bottom\)/,'mobile navigation respects safe areas');
console.log('Road to Send static accessibility and UX checks passed.');
