import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*)<\/script>/)?.[1];
const scoring=JSON.parse(readFileSync(new URL('../src/scoring.json',import.meta.url),'utf8'));
assert.ok(script,'index.html contains an inline application script');
assert.doesNotThrow(()=>new Function(script),'application JavaScript parses');
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);
assert.equal(new Set(ids).size,ids.length,'HTML ids are unique');
for(const id of ['hardestGrade','bountySelect','activityNote','activityDate','identityMember','newParticipantName','proxyMember','endpoint','challengeStart','tripDate','groupGoalInput'])assert.match(html,new RegExp(`<label[^>]+for="${id}"`),`${id} has an associated label`);
for(const tab of ['you','record','crew']){
  assert.match(html,new RegExp(`data-panel="${tab}"`),`${tab} panel exists`);
  assert.match(html,new RegExp(`data-tab="${tab}"`),`${tab} navigation exists`);
}
assert.match(html,/class="bottom-nav"[^>]+aria-label="Primary"/,'bottom navigation is named');
assert.match(html,/id="recordMeter"[^>]+aria-label=/,'record preview meter is accessible');
assert.match(html,/id="syncDiagnostics"[^>]+role="status"[^>]+aria-live="polite"/,'persistent sync diagnostics are announced');
assert.match(html,/id="toast"[^>]+role="status"[^>]+aria-live="polite"/,'toast is announced');
for(const title of ['identityTitle','proxyTitle','setupTitle','confirmTitle','personTitle'])assert.match(html,new RegExp(`role="dialog"[^>]+aria-modal="true"[^>]+aria-labelledby="${title}"`),`${title} dialog is named`);
assert.match(html,/aria-label="Close identity picker"/);
assert.match(html,/aria-label="Close person picker"/);
assert.match(html,/aria-label="Close shared setup"/);
assert.match(html,/aria-label="Close delete confirmation"/);
assert.match(html,/id="confirmOk"[^>]*type="button"/,'the confirm dialog confirms with a real button');
assert.match(html,/id="confirmCancel"[^>]*type="button"/,'the confirm dialog cancels with a real button');
assert.match(script,/function requestDelete\(/,'deleting an entry goes through the confirm request helper');
assert.match(html,/aria-label="Close person details"/);
assert.match(script,/data-person="/,'leaderboard rows expose the climber name as a per-person hook');
assert.match(script,/function openPersonCard\(/,'tapping a climber opens the per-person card');
assert.match(script,/<button class="climber" type="button"[^>]*data-person=/,'the climber name is a real button, not a clickable row');
assert.doesNotMatch(script,/<tr[^>]*tabindex=/,'leaderboard rows stay plain rows without a fake tab stop');
assert.doesNotMatch(script,/[^.\w]confirm\(/,'destructive actions use the in-app dialog, never a native window.confirm');
assert.deepEqual(Object.keys(scoring.categories),['climb','exercise','mobility'],'three categories are configured');
assert.equal(scoring.balancedDayBonus,2,'balanced-day bonus is configured');
assert.equal(scoring.weeklyBountyCap,6,'weekly bounty cap is configured');
assert.ok(Array.isArray(scoring.bounties)&&scoring.bounties.length>=6,'a bounty catalog is present');
assert.ok(scoring.bounties.every(b=>typeof b.id==='string'&&b.id&&typeof b.title==='string'&&b.title&&typeof b.description==='string'&&b.description&&Number.isInteger(b.points)&&b.points>=1&&b.points<=3&&['climb','exercise','mobility'].includes(b.category)),'each bounty has a name, description, integer 1-3 points, and a category');
assert.equal(new Set(scoring.bounties.map(b=>b.id)).size,scoring.bounties.length,'bounty ids are unique across the catalog');
for(const cat of Object.keys(scoring.categories))assert.ok(scoring.bounties.some(b=>b.category===cat),`the ${cat} bounty pool is not empty`);
assert.deepEqual(scoring.grades,['V0','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17']);
const sharedConfig=(script.match(/const GRADES=SCORING\.grades,CATEGORIES=Object\.keys\(SCORING\.categories\)/g)||[]).length;
assert.ok(sharedConfig>=2,'browser and Apps Script both read the shared scoring config');
assert.doesNotMatch(html,/Hard mode|Super hard mode|pull-up mode|Record send pyramid|Balanced week bonus/i,'removed pull-up-mode and legacy features are absent from the UI');
// Saving… was already the label on two buttons (#saveActivityBtn and #saveSetupBtn) before this
// entry, so the preview branch is the third occurrence — a >=2 guard could never have failed.
assert.ok((script.match(/Saving…/g)||[]).length>=3,'the preview reports an in-flight save, on top of the two button labels');
assert.match(script,/Export downloaded\./,'a finished export says so out loud');
assert.match(script,/<button class="cat-chip/,'each category chip is a real button');
assert.match(script,/function prefillCategory\(/,'tapping a chip starts a recording for that category');
assert.match(script,/function breakdownRow\(/,'one breakdown row shape serves the You panel and the person card');
assert.match(script,/function pyramidRow\(/,'one pyramid row shape serves both');
assert.match(script,/function recordsRow\(/,'one records row shape serves both');
assert.equal((script.match(/class="breakdown-row"/g)||[]).length,1,'the breakdown row markup is written once');
assert.equal((script.match(/class="pyramid-row"/g)||[]).length,1,'the pyramid row markup is written once');
// records-row is also the Week in Review leader list's class, and that renderer is another entry's
// surface, so the count here is the two owners of the shape: recordsRow() and renderWeekReview().
assert.equal((script.match(/class="records-row"/g)||[]).length,2,'the You panel and the person card share one records row');
assert.match(script,/#activityList'\)\.innerHTML=activityMarkup\([^)]*,false\)/,'the crew feed is read-only');
assert.match(html,/id="undoBar"[^>]*role="status"[^>]*aria-live="polite"/,'the undo bar announces itself politely');
assert.match(html,/id="undoDelete"[^>]*type="button"/,'undo is a real button');
assert.match(html,/id="undoDismiss"[^>]*type="button"/,'dismissing the undo bar is a real button');
assert.match(html,/id="undoBar"[\s\S]*id="toast"/,'the undo bar sits above the toast in document order');
assert.match(script,/function undoDelete\(/,'a named undo handler restores the row');
assert.match(html,/\.undo-bar:not\(\.hide\)~\.toast\{bottom:160px\}/,'the toast lifts out of the undo bar rather than overlapping it');
assert.match(script,/function writeStore\(/,'the shared storage helper exists');
assert.equal((script.match(/localStorage\.setItem/g)||[]).length,1,'storage writes funnel through one helper');
assert.ok((script.match(/pendingDelete=null/g)||[]).length>=3,'a dismissed confirm clears the pending delete, on top of the declaration and the confirmed path');
assert.match(script,/function computeCreditsRaw\(/,'the raw scorer is separable from the memo that fronts it');
assert.doesNotMatch(script,/\blogs\.(push|splice|unshift|shift|pop|sort|reverse|fill|copyWithin)\(/,'logs is replaced, never mutated in place');
assert.match(script,/Saved to the Sheet, but refresh failed\. Do not retry/,'confirmed saves are distinguished from refresh failures');
assert.match(html,/Climbing[\s\S]*Exercise[\s\S]*Mobility/,'the three categories appear in the record picker');
assert.match(html,/Today's bounties/,'the rotating bounty card is present');
assert.match(html,/id="bountyHint"/,'the Record tab has a slot for the chosen bounty description');
assert.match(html,/id="bountySelect"[^>]*aria-describedby="bountyHint"/,'the bounty select is described by its hint as well as labelled');
assert.match(html,/data-panel="you"[\s\S]*id="bountyCapHint"[\s\S]*id="todayBounties"/,'the weekly bounty-cap progress hint sits in the bounty card head on the You panel');
assert.match(html,/data-panel="you"[\s\S]*today-card[\s\S]*id="bountyCapHint"[\s\S]*id="todayBounties"[\s\S]*class="stat-grid"/,'the bounty card sits directly under the today card, above the stat grid, on the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="todayBounties"[\s\S]*id="personalActivity"[\s\S]*class="stat-grid"/,'the recent activity feed sits above the analytics stat grid on the You panel');
assert.match(script,/function claimBounty\(/,'a claim handler exists so bounty rows are actionable');
assert.match(script,/<button class="bounty" type="button"[^>]*data-claim-bounty=[^>]*aria-label="Claim /,'bounty rows render as labelled one-tap claim buttons');
assert.match(html,/id="bountyHunter"/,'the Bounty Hunter slot is present');
assert.match(html,/id="goalPace"[^>]*role="status"[^>]*aria-live="polite"/,'the goal pace indicator is announced');
assert.match(html,/data-panel="crew"[\s\S]*id="goalPace"[\s\S]*?id="goalProjection"[^>]*role="status"[^>]*aria-live="polite"/,'the goal projection line follows the pace line in the crew panel and is announced');
assert.match(html,/id="youDailyMax"/,'the daily max is rendered from the scoring config');
assert.match(html,/data-panel="you"[\s\S]*id="todayCategories"[^>]*role="list"/,'the per-category chip row is a list inside the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="todayRemaining"[^>]*role="status"[^>]*aria-live="polite"/,'the what-is-left-today line lives in the You panel and is announced');
assert.match(html,/id="youMeter"[^>]*role="img"[^>]*aria-label=/,'the today meter stays a labelled graphic');
assert.match(html,/data-panel="you"[\s\S]*id="youMeter"[\s\S]*id="todayCategories"[\s\S]*id="todayRemaining"[\s\S]*data-tab="record"[\s\S]*id="bountyCapHint"/,'the category chips and remaining line sit between the today meter and the Record button, above the bounty card');
assert.match(script,/function todayProgress\(/,'the today-progress helper backs the category chips');
assert.match(html,/data-panel="you"[\s\S]*id="youCountdown"/,'the personal countdown lives in the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="youPace"[^>]*class="[^"]*pace[^"]*"/,'the personal pace line reuses the crew pace classes inside the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="todayCategories"[\s\S]*id="youCountdown"[\s\S]*id="youPace"[\s\S]*data-tab="record"[\s\S]*id="bountyCapHint"/,'the countdown and personal pace sit between the category chips and the Record button, above the bounty card');
assert.match(script,/function challengeProgress\(/,'the challenge-progress helper backs the personal countdown');
assert.match(script,/function personalPaceInfo\(/,'the personal pace helper backs the personal share line');
assert.match(script,/function setSegmentedMeter\(/,'the You meter renders identifiable per-category segments');
assert.match(html,/data-panel="you"[\s\S]*id="youBreakdown"[\s\S]*data-panel="record"/,'the per-category breakdown card lives inside the You panel');
assert.match(html,/data-panel="you"[\s\S]*class="stat-grid"[\s\S]*id="youTotal"[\s\S]*id="youRank"[\s\S]*id="youStreak"[\s\S]*id="youBestStreak"[\s\S]*data-panel="record"/,'the current and best streak stat cards join the stat grid on the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="youBreakdown"[\s\S]*id="gradePyramid"[\s\S]*id="recordsCard"/,'the grade pyramid card sits between the category breakdown and the personal records card on the You panel');
assert.match(html,/id="gradePyramid"[^>]*role="img"[^>]*aria-label=/,'the grade pyramid is announced as a graphic');
assert.match(html,/data-panel="you"[\s\S]*id="gradePyramidCard"[\s\S]*id="heatmapCard"[\s\S]*id="youHeatmap"/,'the daily activity heatmap card sits after the grade pyramid on the You panel');
assert.match(html,/data-panel="you"[\s\S]*id="gradePyramidCard"[\s\S]*id="recordsCard"[\s\S]*id="heatmapCard"/,'the personal records card sits between the grade pyramid and the heatmap on the You panel');
assert.match(html,/id="youHeatmap"[^>]*role="img"[^>]*aria-label=/,'the daily activity heatmap is announced as a graphic');
assert.match(html,/data-panel="crew"[\s\S]*class="card group-card"[\s\S]*id="weeklyTrendCard"[\s\S]*class="card hunter-card"/,'the weekly trend card sits between the group goal card and the Bounty Hunter card on the crew panel');
assert.match(html,/id="weeklyTrend"[^>]*role="img"[^>]*aria-label=/,'the weekly trend chart is announced as a graphic');
assert.match(html,/class="trend-scroll"[^>]*>\s*<div id="weeklyTrend"/,'the weekly trend chart sits inside a horizontally scrollable wrapper');
assert.match(html,/\.trend-scroll\{overflow-x:auto\}/,'the trend wrapper scrolls horizontally instead of squeezing');
assert.match(html,/id="leaderWeekBtn"[^>]*type="button"[^>]*aria-pressed=/,'the Weekly toggle is a real button with aria-pressed');
assert.match(html,/id="leaderOverallBtn"[^>]*type="button"[^>]*aria-pressed=/,'the Overall toggle is a real button with aria-pressed');
assert.match(html,/id="leaderPointsBtn"[^>]*type="button"[^>]*aria-pressed=/,'the Points toggle is a real button with aria-pressed');
assert.match(html,/id="leaderBountyBtn"[^>]*type="button"[^>]*aria-pressed=/,'the Bounties toggle is a real button with aria-pressed');
assert.match(html,/id="leaderMetricToggle"[^>]*aria-label=/,'the points/bounties metric toggle is a labelled group');
assert.match(html,/id="leaderScopeToggle"[^>]*aria-label=/,'the weekly/overall scope toggle is a labelled group');
assert.match(html,/data-panel="you"[\s\S]*id="youEmptyState"[\s\S]*id="personalActivity"[\s\S]*data-panel="record"/,'the You onboarding empty state sits in the recent-activity area of the You panel');
assert.match(html,/id="youEmptyState"[\s\S]*data-tab="record"/,'the empty state offers a button that jumps to the Record tab');
assert.match(html,/data-panel="crew"[\s\S]*id="crewLocalHint"/,'the crew local-mode hint lives in the Crew panel');
assert.match(html,/data-panel="you"[\s\S]*id="shareBtn"[^>]*type="button"/,'the You panel offers a real Share button');
assert.match(html,/data-panel="you"[\s\S]*id="shareBtn"[\s\S]*today-card/,'the Share button sits in the You page head, above the today card');
assert.equal((script.match(/navigator\.clipboard\.writeText/g)||[]).length,1,'clipboard writes funnel through one helper');
assert.match(script,/function copyText\(/,'the shared clipboard helper exists');
assert.match(script,/function publicUrl\(/,'shared text is built from the endpoint-free public URL');
assert.match(script,/function shareSummary\(/,'the share summary helper backs the Share button');
assert.equal((html.match(/<table[\s>]/g)||[]).length,1,'all crew share one leaderboard');
assert.match(html,/<meta[^>]+name="theme-color"[^>]+content="#f5eee3"/,'a theme-color meta tints the browser chrome to the brand background');
assert.match(html,/<link[^>]+rel="icon"[^>]+href="data:image\/svg\+xml,/,'an inline SVG data-URI favicon is present');
assert.match(html,/<meta[^>]+name="color-scheme"[^>]+content="[^"]*dark[^"]*"/,'a color-scheme meta opts the page into dark rendering');
assert.match(html,/@media\(prefers-color-scheme:dark\)/,'a dark-mode media query overrides the theme variables');
assert.match(html,/env\(safe-area-inset-bottom\)/,'mobile navigation respects safe areas');
console.log('Road to Send static accessibility and UX checks passed.');
