const SCORING=__SCORING_CONFIG__;
const GRADES=SCORING.grades,CATEGORIES=Object.keys(SCORING.categories),CAT_LABELS=SCORING.categoryLabels;
const DAILY_MAX=CATEGORIES.reduce((sum,c)=>sum+SCORING.categories[c],0)+SCORING.balancedDayBonus;
const BOUNTY_BY_ID=new Map(SCORING.bounties.map(b=>[b.id,b]));
const TYPE_ICONS={climb:'climb',exercise:'exercise',mobility:'mobility',bounty:'bounty'};
// One sprite symbol per icon, referenced rather than inlined: the feed draws dozens of these per
// render, so each instance is a <use> of ~40 bytes instead of a repeated path set. Keyed off the
// category name, not SCORING.categoryIcons, so the icon set is a display choice the browser owns
// and changing it never touches the backend contract.
function glyph(k){return `<svg class="glyph" aria-hidden="true"><use href="#g-${k}"/></svg>`}
const TITLE_CATEGORIES=[{id:'crusher',title:'Crusher',type:'climb'},{id:'gym-rat',title:'Gym Rat',type:'exercise'},{id:'yogi',title:'Yogi',type:'mobility'}];
const SCRIPT=__APPS_SCRIPT__;
const SUPPORTED_API_VERSIONS=new Set([__API_VERSION__,11]);// current version leads (drives the "expects vN" displays); 11 is accepted through the v12 rollout so a not-yet-redeployed backend keeps working — its JSON is identical. Drop 11 once every backend is on 12.
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDateOnly(value){const s=String(value||''),m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s);if(!m)return null;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),12);return localDate(d)===s?d:null}
function windowStart(today,days=7){const d=parseDateOnly(String(today||'').slice(0,10));if(!d)return'';d.setDate(d.getDate()-days+1);return localDate(d)}
function weekKey(value){const d=parseDateOnly(String(value||'').slice(0,10));if(!d)return'0000-00-00';d.setDate(d.getDate()-(d.getDay()+6)%7);return localDate(d)}
function dateInTimeZone(date,timeZone){try{const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),get=x=>parts.find(p=>p.type===x)?.value;return`${get('year')}-${get('month')}-${get('day')}`}catch{return''}}
function defaultConfig(){const d=new Date(),end=new Date(d);end.setDate(end.getDate()+69);return{startDate:localDate(d),tripDate:localDate(end),goal:500,crew:[]}}
function safeJson(key,fallback,accept=()=>true){try{const raw=localStorage.getItem(key);if(raw===null)return fallback;const value=JSON.parse(raw);return accept(value)?value:fallback}catch{return fallback}}
function normalizeCrew(value){const seen=new Set();return(Array.isArray(value)?value:[]).map(x=>({name:(typeof x==='string'?x:String(x&&x.name||'')).trim()})).filter(x=>{const key=x.name.toLowerCase();if(!x.name||x.name.length>30||seen.has(key))return false;seen.add(key);return true})}
function parseRemoteConfig(value,remoteErrors){const errors={};for(const item of Array.isArray(remoteErrors)?remoteErrors:[]){if(item&&item.field)errors[item.field+(item.value?'_'+item.value:'')]=`${item.value?item.value+': ':''}${item.reason||'is invalid'}`}if(!value||typeof value!=='object'||Array.isArray(value))return{value:null,errors};const startDate=String(value.startDate||''),tripDate=String(value.tripDate||''),goal=Number(value.goal),crew=normalizeCrew(value.crew);if(!parseDateOnly(startDate))errors.challengeStart='Challenge start must use YYYY-MM-DD.';if(!parseDateOnly(tripDate))errors.tripDate='Challenge end must use YYYY-MM-DD.';if(parseDateOnly(startDate)&&parseDateOnly(tripDate)&&startDate>tripDate)errors.challengeStart='Challenge start must be on or before the end.';if(!Number.isInteger(goal)||goal<50||goal>10000)errors.groupGoal='Group goal must be a whole number from 50 to 10,000.';return{value:Object.keys(errors).some(k=>['challengeStart','tripDate','groupGoal'].includes(k))?null:{startDate,tripDate,goal,crew},errors}}
function sanitizeConfig(value,fallback=defaultConfig()){return parseRemoteConfig(value,[]).value||fallback}
// Every field below arrives untrusted: normalizeActivityRow in the Apps Script keeps a date it could
// not parse rather than dropping the row, and SUPPORTED_API_VERSIONS still accepts a v11 backend that
// predates some of these checks. Coerce each field to the shape src/schema.json declares, in place, so
// an unknown Sheet column survives untouched — and normalize rather than reject, because an entry that
// disappears is a climber's logged session gone. The date is matched whole, not sliced: a time suffix is
// dropped, but only a real hh:mm time may follow the day — trailing junk like '2026-07-13not-a-date'
// or '2026-07-13Tnot-a-date' is not a date the schema allows, so it blanks out rather than truncating.
// `name` stays raw on purpose: nameKey() and totalsModel() already trim it at every point of use,
// and two assertions pin that pass-through.
function normalizeActivity(x){const stamp=/^(\d{4}-\d{2}-\d{2})(?:[T ]\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:?\d{2})?)?$/.exec(String(x.date||'').trim()),date=stamp&&parseDateOnly(stamp[1])?stamp[1]:'',grade=String(x.hardestGrade||'').trim().toUpperCase();return Object.assign({},x,{id:x.id==null?'':String(x.id),category:CATEGORIES.includes(x.category)?x.category:'',points:Math.max(0,Math.min(3,Math.round(Number(x.points)||0))),date,createdAt:String(x.createdAt||''),hardestGrade:GRADES.includes(grade)?grade:'',bountyId:String(x.bountyId||'').slice(0,40),bountyTitle:String(x.bountyTitle||'').slice(0,60),note:String(x.note||'').slice(0,120)})}
function sanitizeActivities(value){return Array.isArray(value)?value.filter(x=>x&&typeof x==='object'&&!Array.isArray(x)&&['climb','exercise','mobility','bounty'].includes(x.type)):[]}
// Only remote rows and the cache derived from them are normalized. roadToSendLogsV9 is a frozen key
// holding rows this app itself wrote, and persistLocal() writes logs straight back to it — running
// them through the Sheet normalizer would rewrite a climber's stored history on their next add.
function normalizeActivities(value){return sanitizeActivities(value).map(normalizeActivity)}
function bountyById(id){return BOUNTY_BY_ID.get(String(id||''))||null}
function hashText(text){let h=2166136261;const s=String(text);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function dailyBounties(date){const day=String(date||'').slice(0,10);return CATEGORIES.map(cat=>{const pool=SCORING.bounties.filter(b=>b.category===cat);return pool.length?pool[hashText(day+'|'+cat)%pool.length]:null}).filter(Boolean)}
function activityPoints(x){if(!x)return 0;if(x.type==='bounty')return(bountyById(x.bountyId)||{}).points||0;return SCORING.categories[x.type]||0}
const creditKey=(x,i)=>x.id||i;
const nameKey=x=>String(x&&x.name||'').trim().toLowerCase();
const state=globalThis.state={creditMemo:null,creditRuns:0,endpoint:'',incoming:undefined,logs:[],config:defaultConfig(),me:'',recordingFor:'',lastSyncedAt:0,protocolVersion:0,serverDate:'',challengeTimeZone:'',syncState:'local',syncDetail:'',syncErrorCode:'',configErrors:{},requestSerial:0,renderedDay:'',leaderMetric:'points',leaderScope:'week',bountyWeekOpen:false,claimedOpen:false,personCardName:'',lastFocused:null,gradeDefaultApplied:'',gradeChosen:false,saving:false,pendingDelete:null,confirmAction:null,crewFeedLimit:20,personalFeedLimit:5,feedType:'all',crewFeedType:'all',lastDeleted:null};
function dateInChallenge(date,settings=state.config){return Boolean(parseDateOnly(date)&&parseDateOnly(settings&&settings.startDate)&&parseDateOnly(settings&&settings.tripDate)&&date>=settings.startDate&&date<=settings.tripDate)}
function paceInfo(total,settings=state.config,today=challengeToday()){const start=parseDateOnly(settings&&settings.startDate),end=parseDateOnly(settings&&settings.tripDate),now=parseDateOnly(today),goal=Number(settings&&settings.goal);if(!start||!end||!now||!Number.isFinite(goal)||goal<=0||settings.startDate>settings.tripDate)return null;if(total>=goal)return{state:'met'};if(today<settings.startDate)return{state:'before'};if(today>settings.tripDate)return{state:'ended',short:goal-total};const day=86400000,totalDays=Math.round((end-start)/day)+1,elapsed=Math.round((now-start)/day)+1,expected=Math.round(goal*elapsed/totalDays),diff=total-expected,perDay=Math.ceil((goal-total)/(totalDays-elapsed+1));return{state:Math.abs(diff)<=2?'on':diff>0?'ahead':'behind',diff,perDay}}
function projectedTotal(total,settings,today){const start=parseDateOnly(settings&&settings.startDate),end=parseDateOnly(settings&&settings.tripDate),now=parseDateOnly(today),goal=Number(settings&&settings.goal);if(!start||!end||!now||!Number.isFinite(goal)||goal<=0||settings.startDate>settings.tripDate||today<settings.startDate||today>settings.tripDate)return null;const day=86400000,totalDays=Math.round((end-start)/day)+1,elapsed=Math.round((now-start)/day)+1;if(elapsed<3)return null;const rate=total/elapsed,projected=Math.round(rate*totalDays);if(rate>0&&goal<=projected){const hit=new Date(start);hit.setDate(hit.getDate()+Math.min(Math.ceil(goal/rate),totalDays)-1);return{projected,goalDate:localDate(hit)}}return{projected}}
function computeCreditsRaw(entries,settings){state.creditRuns++;const info=new Map(),weeks=new Map(),totals=new Map(),dayMeter=new Map(),dayTotal=new Map(),bountyWeekCount=new Map(),bountyTotal=new Map(),bountyUsed=new Map(),daySeen=new Map(),bonusGiven=new Set(),inWin=[];entries.forEach((x,i)=>{const base=activityPoints(x);if(!dateInChallenge(x.date,settings)){info.set(creditKey(x,i),{base,credit:0,reason:'outside challenge'});return}inWin.push({x,i,base})});inWin.sort((a,b)=>String(a.x.date).localeCompare(String(b.x.date))||String(a.x.createdAt||'').localeCompare(String(b.x.createdAt||''))||String(a.x.id||'').localeCompare(String(b.x.id||''))||a.i-b.i);const addWeek=(nm,wk,p)=>weeks.set(nm+'|'+wk,(weeks.get(nm+'|'+wk)||0)+p),addTotal=(nm,p)=>totals.set(nm,(totals.get(nm)||0)+p),addMeter=(nm,d,p)=>dayMeter.set(nm+'|'+d,Math.min(DAILY_MAX,(dayMeter.get(nm+'|'+d)||0)+p)),addDayTotal=(nm,d,p)=>dayTotal.set(nm+'|'+d,(dayTotal.get(nm+'|'+d)||0)+p);for(const {x,i,base} of inWin){const nm=nameKey(x),wk=weekKey(x.date),d=String(x.date).slice(0,10),dk=nm+'|'+d;if(x.type==='bounty'){bountyWeekCount.set(nm+'|'+wk,(bountyWeekCount.get(nm+'|'+wk)||0)+1);bountyTotal.set(nm,(bountyTotal.get(nm)||0)+1);const used=bountyUsed.get(nm+'|'+wk)||0,credit=Math.max(0,Math.min(base,SCORING.weeklyBountyCap-used));bountyUsed.set(nm+'|'+wk,used+credit);info.set(creditKey(x,i),{base,credit,reason:credit<base?'weekly cap':''});addWeek(nm,wk,credit);addTotal(nm,credit);addDayTotal(nm,d,credit);continue}if(!daySeen.has(dk))daySeen.set(dk,new Set());const seen=daySeen.get(dk);let credit,reason='';if(seen.has(x.type)){credit=0;reason='already logged'}else{credit=base;seen.add(x.type)}info.set(creditKey(x,i),{base,credit,reason});addWeek(nm,wk,credit);addTotal(nm,credit);addMeter(nm,d,credit);addDayTotal(nm,d,credit);if(!bonusGiven.has(dk)&&CATEGORIES.every(c=>seen.has(c))){bonusGiven.add(dk);addWeek(nm,wk,SCORING.balancedDayBonus);addTotal(nm,SCORING.balancedDayBonus);addMeter(nm,d,SCORING.balancedDayBonus);addDayTotal(nm,d,SCORING.balancedDayBonus)}}return{info,weeks,totals,dayMeter,dayTotal,bountyWeekCount,bountyTotal}}
function computeCredits(entries,settings=state.config){if(entries!==state.logs||settings!==state.config)return computeCreditsRaw(entries,settings);if(state.creditMemo&&state.creditMemo.ref===entries&&state.creditMemo.len===entries.length&&state.creditMemo.cfg===settings)return state.creditMemo.value;const value=computeCreditsRaw(entries,settings);state.creditMemo={ref:entries,len:entries.length,cfg:settings,value};return value}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDay(value){const date=String(value||'').slice(0,10),now=challengeToday();if(date===now)return'Today';const prior=parseDateOnly(now);if(prior){prior.setDate(prior.getDate()-1);if(date===localDate(prior))return'Yesterday'}const d=parseDateOnly(date);return d?d.toLocaleDateString('en-US',{month:'short',day:'numeric'}):date}
function meterMarkup(points){const n=Math.max(0,Math.min(DAILY_MAX,Number(points)||0));return Array.from({length:DAILY_MAX},(_,i)=>`<i class="${i<n?'filled':''}"></i>`).join('')}
function cacheKey(kind,url=state.endpoint){return`roadToSendShared:${kind}:${encodeURIComponent(url)}`}
function loadInitialState(){resetFeedLimits();state.endpoint=localStorage.getItem('roadToSendEndpoint')||'';state.incoming=new URLSearchParams(location.search);if(state.incoming.get('sheet')){state.endpoint=state.incoming.get('sheet').trim();writeStore('roadToSendEndpoint',state.endpoint)}state.me=localStorage.getItem('roadToSendMe')||'';if(state.endpoint){state.logs=normalizeActivities(safeJson(cacheKey('activities'),[],Array.isArray));state.config=sanitizeConfig(safeJson(cacheKey('config'),defaultConfig(),x=>x&&typeof x==='object'));const meta=safeJson(cacheKey('meta'),{},x=>x&&typeof x==='object');state.lastSyncedAt=Number(meta.lastSyncedAt)||0;state.protocolVersion=Number(meta.protocolVersion)||0;state.serverDate=String(meta.serverDate||'');state.challengeTimeZone=String(meta.timeZone||'');state.syncState=state.lastSyncedAt?'stale':'loading'}else{if(localStorage.getItem('roadToSendConfigV9')===null&&localStorage.getItem('roadToSendConfigV8')!==null)writeStore('roadToSendConfigV9',JSON.stringify(sanitizeConfig(safeJson('roadToSendConfigV8',defaultConfig(),x=>x&&typeof x==='object'))));state.logs=sanitizeActivities(safeJson('roadToSendLogsV9',[],Array.isArray));state.config=sanitizeConfig(safeJson('roadToSendConfigV9',defaultConfig(),x=>x&&typeof x==='object'));state.syncState='local'}state.recordingFor=state.me}
function writeStore(key,value){try{const store=typeof localStorage==='undefined'?null:localStorage;if(!store||typeof store.setItem!=='function')return false;localStorage.setItem(key,value);return true}catch{return false}}
function persistShared(){if(!state.endpoint)return false;const a=writeStore(cacheKey('activities'),JSON.stringify(state.logs)),b=writeStore(cacheKey('config'),JSON.stringify(state.config)),c=writeStore(cacheKey('meta'),JSON.stringify({lastSyncedAt:state.lastSyncedAt,protocolVersion:state.protocolVersion,serverDate:state.serverDate,timeZone:state.challengeTimeZone}));return a&&b&&c}
function persistLocal(){const a=writeStore('roadToSendLogsV9',JSON.stringify(state.logs)),b=writeStore('roadToSendConfigV9',JSON.stringify(state.config));return a&&b}
function challengeToday(){if(!state.endpoint)return localDate();const zoned=dateInTimeZone(new Date(),state.challengeTimeZone);if(zoned)return zoned;return state.serverDate&&state.lastSyncedAt&&localDate(new Date(state.lastSyncedAt))===localDate()?state.serverDate:localDate()}
function participant(name){return state.config.crew.find(x=>x.name.toLowerCase()===String(name||'').trim().toLowerCase())}
function currentTarget(){return participant(state.recordingFor)||participant(state.me)||null}
function totalsModel(){const credits=computeCredits(state.logs),today=challengeToday(),wk=weekKey(today),start=windowStart(today),names=new Map(),recentBountyCounts=new Map(),recentTotals=new Map();for(const p of state.config.crew)names.set(p.name.toLowerCase(),p.name);state.logs.forEach(x=>{const d=String(x.name||'').trim();if(d&&!names.has(d.toLowerCase()))names.set(d.toLowerCase(),d);const date=String(x&&x.date||'').slice(0,10),lower=nameKey(x);if(x.type==='bounty'&&dateInChallenge(date)&&date>=start&&date<=today)recentBountyCounts.set(lower,(recentBountyCounts.get(lower)||0)+1)});credits.dayTotal.forEach((points,key)=>{const cut=key.indexOf('|'),lower=key.slice(0,cut),date=key.slice(cut+1);if(date>=start&&date<=today)recentTotals.set(lower,(recentTotals.get(lower)||0)+points)});const sorted=[...names.entries()].map(([lower,name])=>({name,total:credits.totals.get(lower)||0,week:credits.weeks.get(lower+'|'+wk)||0,recent:recentTotals.get(lower)||0,bounties:credits.bountyWeekCount.get(lower+'|'+wk)||0,recentBounties:recentBountyCounts.get(lower)||0,bountiesTotal:credits.bountyTotal.get(lower)||0})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));const maxB=Math.max(0,...sorted.map(x=>x.recentBounties)),hunters=maxB>0?sorted.filter(x=>x.recentBounties===maxB).map(x=>x.name):[];return Object.assign({},credits,{sorted,total:sorted.reduce((sum,x)=>sum+x.total,0),hunters,huntCount:maxB})}
function rankLabel(rank,field){return!Number.isInteger(rank)||rank<=0||field<rank?'—':'#'+rank+' of '+field}
function rankLeaders(rows,metric){return[...rows].sort((a,b)=>(Number(b[metric])||0)-(Number(a[metric])||0)||a.name.localeCompare(b.name))}
function prevWeekKey(today){const wk=parseDateOnly(weekKey(String(today||'').slice(0,10)));if(!wk)return'';wk.setDate(wk.getDate()-7);return localDate(wk)}
function weekTrend(nameLower,today){const end=String(today||'').slice(0,10),recentStart=windowStart(end),earlierStart=windowStart(end,14),earlierEndDate=parseDateOnly(recentStart);if(!recentStart||!earlierStart||!earlierEndDate)return null;earlierEndDate.setDate(earlierEndDate.getDate()-1);const earlierEnd=localDate(earlierEndDate);if(earlierEnd<state.config.startDate)return null;const {dayTotal}=computeCredits(state.logs),key=String(nameLower||'').toLowerCase(),sum=(start,finish)=>{let total=0;dayTotal.forEach((points,dayKey)=>{const cut=dayKey.indexOf('|'),name=dayKey.slice(0,cut),date=dayKey.slice(cut+1);if(name===key&&date>=start&&date<=finish)total+=points});return total},now=sum(recentStart,end),before=sum(earlierStart,earlierEnd);return now>before?'up':now<before?'down':'even'}
function weeksUntilDone(today=challengeToday(),settings=state.config){if(!parseDateOnly(today)||!parseDateOnly(settings&&settings.tripDate)||!parseDateOnly(settings&&settings.startDate))return null;if(today>settings.tripDate)return{done:true};const end=parseDateOnly(settings.tripDate),now=parseDateOnly(today),days=Math.round((end-now)/86400000)+1;return{days,weeks:Math.ceil(days/7)}}
function challengeProgress(today=challengeToday(),settings=state.config){const start=parseDateOnly(settings&&settings.startDate),end=parseDateOnly(settings&&settings.tripDate),now=parseDateOnly(today);if(!start||!end||!now||settings.startDate>settings.tripDate)return null;const d=86400000,totalDays=Math.round((end-start)/d)+1,left=weeksUntilDone(today,settings)||{},state=today<settings.startDate?'before':today>settings.tripDate?'ended':'active',ended=state==='ended',day=state==='before'?0:Math.min(totalDays,Math.round((now-start)/d)+1);return{state,day,totalDays,daysLeft:ended?0:left.days||0,weeksLeft:ended?0:left.weeks||0,pct:Math.round(day/totalDays*100)}}
function personalPaceInfo(nameLower,today=challengeToday(),settings=state.config,model=totalsModel()){const crewSize=Math.max(1,model.sorted.length||(state.config.crew||[]).length),share=Math.ceil(Number(settings&&settings.goal)/crewSize),total=model.totals.get(nameLower)||0;return{share,total,pace:paceInfo(total,Object.assign({},settings,{goal:share}),today)}}
function weekReviewModel(today=challengeToday()){const prevWk=prevWeekKey(today),{weeks,bountyWeekCount,dayTotal}=computeCredits(state.logs),names=new Map();for(const p of state.config.crew)names.set(p.name.toLowerCase(),p.name);state.logs.forEach(x=>{const d=String(x.name||'').trim();if(d&&!names.has(d.toLowerCase()))names.set(d.toLowerCase(),d)});const leaders=prevWk?[...names.entries()].map(([lower,name])=>({name,points:weeks.get(lower+'|'+prevWk)||0})).filter(x=>x.points>0).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name)).slice(0,3):[];const bountyRows=prevWk?[...names.entries()].map(([lower,name])=>({name,count:bountyWeekCount.get(lower+'|'+prevWk)||0})):[],maxB=Math.max(0,...bountyRows.map(x=>x.count)),hunters=maxB>0?bountyRows.filter(x=>x.count===maxB).map(x=>x.name):[];const meLower=String(state.me).toLowerCase(),myPoints=prevWk?(weeks.get(meLower+'|'+prevWk)||0):0;let myActiveDays=0;dayTotal.forEach((v,k)=>{if(v>=1&&k.startsWith(meLower+'|')&&weekKey(k.slice(meLower.length+1))===prevWk)myActiveDays++});const myGradeIdx=state.logs.filter(x=>x.type==='climb'&&nameKey(x)===meLower&&weekKey(x.date)===prevWk).map(x=>GRADES.indexOf(String(x.hardestGrade||''))).filter(i=>i>=0),myHardest=myGradeIdx.length?GRADES[Math.max(...myGradeIdx)]:'';return{prevWk,leaders,hunters,huntCount:maxB,mine:{points:myPoints,activeDays:myActiveDays,hardest:myHardest},weeksLeft:weeksUntilDone(today)}}
function setMeter(selector,points,label){const el=document.querySelector(selector);if(!el)return;const cached=el.__meterState;if(cached&&cached.value===points&&cached.label===label)return;el.__meterState={value:points,label};el.style.gridTemplateColumns=`repeat(${DAILY_MAX},1fr)`;el.innerHTML=meterMarkup(points);el.setAttribute('aria-label',label)}
function feedEmptyCopy(type){return type&&type!=='all'&&CATEGORIES.includes(type)?`No ${CAT_LABELS[type]||type} entries in this view.`:'No activity yet.'}
// One display name for a logged bounty, shared by the feed, the delete confirmation and the
// undo bar, so a row whose bountyTitle cell is blank still reads by name everywhere.
function bountyTitle(x){return x&&x.bountyTitle||(bountyById(x&&x.bountyId)||{}).title||'Bounty'}
function activityMarkup(items,limit,allowDelete){const {info}=computeCredits(state.logs);let lastDay='';return items.map((x,i)=>({x,i:state.logs.indexOf(x)})).sort((a,b)=>String(b.x.date).localeCompare(String(a.x.date))||String(b.x.createdAt||'').localeCompare(String(a.x.createdAt||''))).slice(0,limit).map(({x,i})=>{const c=info.get(creditKey(x,i))||{base:activityPoints(x),credit:0},title=x.type==='bounty'?bountyTitle(x):CAT_LABELS[x.type]||x.type,detail=x.type==='climb'?`${CAT_LABELS.climb}${x.hardestGrade?' · '+esc(x.hardestGrade):''}${x.note?' · '+esc(x.note):''}`:x.type==='bounty'?`${esc(title)}${x.note?' · '+esc(x.note):''}`:`${esc(CAT_LABELS[x.type]||x.type)}${x.note?' · '+esc(x.note):''}`,note={'outside challenge':'outside window','already logged':'already logged today','weekly cap':'weekly bounty cap'}[c.reason]||(c.credit<c.base?`${c.base} generated`:''),score=`<strong>+${c.credit}</strong>${note?`<small>${note}</small>`:''}`,del=allowDelete?`<button class="del" type="button" data-del="${i}"${x.id?` data-id="${esc(x.id)}"`:''} aria-label="Delete ${esc(title)} for ${esc(x.name)}">×</button>`:'',nm=esc(x.name),who=allowDelete?`<strong>${nm}</strong>`:`<button class="climber" type="button" data-person="${nm}" aria-haspopup="dialog" aria-label="Open ${nm}'s details">${nm}</button>`;const day=String(x.date||'').slice(0,10),head=day===lastDay?'':`<h3 class="activity-day">${esc(fmtDay(day))}</h3>`;lastDay=day;return`${head}<div class="activity"><div class="avatar">${glyph(TYPE_ICONS[x.type]||'climb')}</div><div>${who}<small>${detail}</small></div><div class="pts">${score}</div>${del}</div>`}).join('')||`<p class="hint">${feedEmptyCopy(allowDelete?state.feedType:state.crewFeedType)}</p>`}
function bountyWeekProgress(nameLower,today){const {info}=computeCredits(state.logs),wk=weekKey(today);let credited=0;state.logs.forEach((x,i)=>{if(x.type!=='bounty'||nameKey(x)!==nameLower||weekKey(x.date)!==wk)return;const c=info.get(creditKey(x,i));if(c)credited+=c.credit});return credited}
function categoryDays(nameLower,type,today){const {info}=computeCredits(state.logs),start=windowStart(today),key=String(nameLower||'').toLowerCase();let days=0;state.logs.forEach((x,i)=>{const date=String(x&&x.date||'').slice(0,10),credit=info.get(creditKey(x,i));if(nameKey(x)===key&&x.type===type&&date>=start&&date<=today&&credit&&credit.credit>0)days++});return days}
function crewTitles(today,model=totalsModel()){const rows=model.sorted;return TITLE_CATEGORIES.map(item=>{const values=rows.map(row=>({name:row.name,days:categoryDays(row.name.toLowerCase(),item.type,today)})),max=Math.max(0,...values.map(row=>row.days)),holders=max>0?values.filter(row=>row.days===max).map(row=>row.name):[];return{id:item.id,title:item.title,holders}})}
function prefillCategory(type){const radio=document.querySelector('input[name="activityType"][value="'+type+'"]');if(!radio)return;setDefaultRecordDate();const dateBox=document.querySelector('#dateFields');if(dateBox)dateBox.classList.add('hide');const dateToggleEl=document.querySelector('#dateToggle');if(dateToggleEl){dateToggleEl.setAttribute('aria-expanded','false');dateToggleEl.textContent='＋ Different day'}radio.checked=true;showTab('record');updateRecordPreview()}
function claimBounty(id){const b=bountyById(id);if(!b)return;setDefaultRecordDate();const dateBox=document.querySelector('#dateFields');if(dateBox)dateBox.classList.add('hide');const dateToggleEl=document.querySelector('#dateToggle');if(dateToggleEl){dateToggleEl.setAttribute('aria-expanded','false');dateToggleEl.textContent='＋ Different day'}const radio=document.querySelector('input[name="activityType"][value="bounty"]');if(radio)radio.checked=true;showTab('record');populateBountySelect();const select=document.querySelector('#bountySelect');if(select)select.value=b.id;updateRecordPreview();if(select&&select.focus)select.focus()}
function upcomingBounties(today,days=7){const start=parseDateOnly(String(today||'').slice(0,10));if(!start)return[];const end=parseDateOnly(String(state.config.tripDate||'').slice(0,10)),out=[];for(let i=1;i<=days;i++){const d=new Date(start);d.setDate(d.getDate()+i);if(end&&d>end)break;const date=localDate(d);out.push({date,label:fmtDay(date),bounties:dailyBounties(date)})}return out}
function renderBountyWeek(){const box=document.querySelector('#bountyWeek'),toggle=document.querySelector('#bountyWeekToggle');if(!box||!toggle)return;toggle.setAttribute('aria-expanded',String(state.bountyWeekOpen));box.classList.toggle('hide',!state.bountyWeekOpen);if(!state.bountyWeekOpen){box.innerHTML='';return}const days=upcomingBounties(challengeToday());box.innerHTML=days.length?days.map(d=>`<div class="bounty-day"><h3>${esc(d.label)}</h3>${d.bounties.map(b=>`<div class="bounty-peek"><span class="bounty-cat" aria-hidden="true">${glyph(b.category)}</span><span><strong>${esc(b.title)}</strong><small>${esc(b.description)}</small></span><span class="bounty-pts">+${b.points}</span></div>`).join('')}</div>`).join(''):'<p class="hint">No days left in the challenge.</p>'}
function toggleBountyWeek(){state.bountyWeekOpen=!state.bountyWeekOpen;renderBountyWeek()}
function claimedBounties(nameLower){const key=String(nameLower||'');if(!key)return[];const {info}=computeCredits(state.logs);return state.logs.filter(x=>x&&x.type==='bounty'&&nameKey(x)===key).map(x=>{const c=info.get(creditKey(x,state.logs.indexOf(x)))||{base:activityPoints(x),credit:0};return{x,base:c.base,credit:c.credit}}).sort((a,b)=>String(b.x.date).localeCompare(String(a.x.date))||String(b.x.createdAt||'').localeCompare(String(a.x.createdAt||''))).map(({x,base,credit})=>({date:fmtDay(x.date),label:x.bountyTitle||(bountyById(x.bountyId)||{}).title||'Bounty',note:String(x.note||''),base,credit}))}
function claimedTodayIds(nameLower,today){const day=String(today||'').slice(0,10),ids=new Set();state.logs.forEach(x=>{if(x&&x.type==='bounty'&&nameKey(x)===nameLower&&String(x.date).slice(0,10)===day)ids.add(String(x.bountyId||''))});return ids}
function claimedCaption(rows){if(!rows||!rows.length)return'';const n=rows.length,points=rows.reduce((total,r)=>total+r.credit,0);return`${n} claim${n===1?'':'s'} · ${points} point${points===1?'':'s'} counted`}
// Two bounty-peek owners: renderBountyWeek() for upcoming days and claimedRow() for claims.
function claimedRow(r){return`<div class="bounty-peek"><span class="bounty-cat" aria-hidden="true">${glyph('bounty')}</span><span><strong>${esc(r.label)}</strong><small>${esc(r.date)}${r.note?' · '+esc(r.note):''}${r.credit<r.base?' · weekly bounty cap':''}</small></span><span class="bounty-pts">+${r.credit}</span></div>`}
function personRecent(nameLower,limit=5){const key=String(nameLower||'');if(!key)return[];return state.logs.filter(x=>x&&nameKey(x)===key).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,limit).map(x=>({label:x.type==='bounty'?(x.bountyTitle||(bountyById(x.bountyId)||{}).title||'Bounty'):`${CAT_LABELS[x.type]||x.type}${x.hardestGrade?' · '+x.hardestGrade:''}`,value:fmtDay(x.date)}))}
function renderClaimed(){const box=document.querySelector('#claimedList'),toggle=document.querySelector('#claimedToggle'),cap=document.querySelector('#claimedSummary');if(!box||!toggle)return;toggle.setAttribute('aria-expanded',String(state.claimedOpen));box.classList.toggle('hide',!state.claimedOpen);if(!state.claimedOpen){box.innerHTML='';if(cap)cap.textContent='';return}const rows=claimedBounties(String(state.me).toLowerCase());box.innerHTML=rows.length?rows.map(claimedRow).join(''):'<p class="hint">No bounty claims yet.</p>';if(cap)cap.textContent=claimedCaption(rows)}
function toggleClaimed(){state.claimedOpen=!state.claimedOpen;renderClaimed()}
function renderBounties(){renderBountyWeek();renderClaimed();const today=challengeToday(),claimed=claimedTodayIds(String(state.me).toLowerCase(),today),list=dailyBounties(today),card=document.querySelector('#todayBounties');if(card)card.innerHTML=list.map(b=>{const suffix=claimed.has(b.id)?' · claimed today':'';const done=claimed.has(b.id);return`<button class="bounty${done?' done':''}" type="button" data-claim-bounty="${esc(b.id)}" aria-label="Claim ${esc(b.title)} · ${esc(CAT_LABELS[b.category])} bounty · plus ${b.points} point${b.points===1?'':'s'}${suffix}"><div class="bounty-cat" aria-hidden="true">${glyph(done?'check':b.category)}</div><div><strong>${esc(b.title)}</strong><small>${esc(b.description)}${suffix}</small></div><div class="pts">+${b.points}</div><span class="bounty-go" aria-hidden="true">›</span></button>`}).join('')||'<p class="hint">No bounties today.</p>';const hint=document.querySelector('#bountyCapHint');if(hint){const cap=SCORING.weeklyBountyCap,credited=bountyWeekProgress(String(state.me).toLowerCase(),today);hint.textContent=`${credited} / ${cap} bounty points this week${credited>=cap?' · capped — more claims still count toward the Bounty Hunter tag':''}`}}
function todayProgress(nameLower,today){const day=String(today||'').slice(0,10),inWindow=dateInChallenge(day),{info,dayMeter}=computeCredits(state.logs),seen=new Set();state.logs.forEach((x,i)=>{if(nameKey(x)!==nameLower||String(x&&x.date||'').slice(0,10)!==day||CATEGORIES.indexOf(x.type)<0)return;const c=info.get(creditKey(x,i));if(c&&c.reason!=='outside challenge')seen.add(x.type)});const rows=CATEGORIES.map(t=>({type:t,label:CAT_LABELS[t]||t,icon:t,points:SCORING.categories[t],logged:seen.has(t)})),loggedCount=rows.filter(r=>r.logged).length,remainingPoints=rows.reduce((sum,r)=>sum+(r.logged?0:r.points),0),bonusPoints=SCORING.balancedDayBonus,bonusEarned=rows.length>0&&loggedCount===rows.length,points=dayMeter.get(nameLower+'|'+day)||0;return{today:day,inWindow,points,max:DAILY_MAX,rows,loggedCount,remainingPoints,bonusPoints,bonusEarned,bonusReachable:inWindow&&!bonusEarned,potential:inWindow?points+remainingPoints+(bonusEarned?0:bonusPoints):points}}
function todayPillState(prog){const cls=prog&&prog.points>=prog.max?'max':'';if(!prog)return{text:'Ready',cls};if(prog.bonusEarned)return{text:'Balanced day',cls};if(prog.loggedCount>0)return{text:`${prog.rows.length-prog.loggedCount} more for +${prog.bonusPoints}`,cls};if(prog.inWindow)return{text:'Ready',cls};return{text:parseDateOnly(state.config.tripDate)&&prog.today>state.config.tripDate?'Complete':'Not started',cls}}
function meterSegments(prog){const segs=[];(prog&&prog.rows||[]).forEach(r=>{for(let i=0;i<r.points;i++)segs.push({cls:'seg-'+r.type+(r.logged?' filled':''),label:r.label})});for(let i=0;i<(prog?prog.bonusPoints:0);i++)segs.push({cls:'seg-bonus'+(prog&&prog.bonusEarned?' filled':''),label:`+${prog.bonusPoints} balanced-day bonus`});return segs}
function joinLabels(items){return items.length>1?items.slice(0,-1).join(', ')+' and '+items[items.length-1]:items[0]||''}
// Grouped-pip goal ring. Draws the same eight day segments meterSegments() feeds the bar meter,
// laid out as 3·2·1·2 arc groups so the shape of a day reads at a glance. Geometry only — the
// pips, their classes and their filled state all still come from the scoring core.
function ringGroups(prog){return (prog&&prog.rows||[]).map(r=>r.points).concat(prog&&prog.bonusPoints?[prog.bonusPoints]:[])}
// A round stroke cap overhangs its arc by half the stroke width, which at r=48 is another
// RING_CAP degrees off each end. Both gaps are therefore measured, not guessed: the old fixed 10deg
// in-group gap was narrower than the 10.7deg of cap growing into it, which is why the pips touched.
// Deriving them from RING_W means a future stroke change cannot silently close them again.
const RING_R=48,RING_W=7,RING_CAP=(RING_W/2/RING_R)*180/Math.PI,RING_GAP=5+2*RING_CAP,RING_SPLIT=15+2*RING_CAP;
// `filled` is the per-pip banked flag. Where two banked pips meet inside the same group, each
// reaches half way across the gap between them so their round caps touch: a category you have
// banked stops being three pips and becomes one arc. The splits between groups never bridge —
// they are what makes the 3-2-1-2 shape of a day readable — so a sealed day closes them with the
// gold seal circle instead, which is the one state where the whole ring is a single shape.
function ringArcs(groups,filled){const n=groups.reduce((a,b)=>a+b,0);if(!n)return[];const span=(360-(n-groups.length)*RING_GAP-groups.length*RING_SPLIT)/n,out=[],inGroup=[];let a=-90;groups.forEach(g=>{for(let k=0;k<g;k++){out.push([a,a+span]);inGroup.push(k<g-1);a+=span+(k<g-1?RING_GAP:RING_SPLIT)}});const on=i=>Boolean(filled&&filled[i]),merged=out.map(x=>x.slice());for(let i=0;i<n-1;i++){if(!inGroup[i]||!on(i)||!on(i+1))continue;const gap=(out[i+1][0]-out[i][1])/2;merged[i][1]+=gap;merged[i+1][0]-=gap}return merged}
function ringPath(a1,a2){const at=a=>{const t=a*Math.PI/180;return(60+RING_R*Math.cos(t)).toFixed(1)+' '+(60+RING_R*Math.sin(t)).toFixed(1)};return`M${at(a1)}A${RING_R} ${RING_R} 0 ${a2-a1>180?1:0} 1 ${at(a2)}`}
// render() runs on every state change, and assigning innerHTML replaces the nodes underneath --
// which restarts any CSS animation on them. Without this the bar and trend reveals would replay
// on refreshes that changed nothing, including shared mode's polling. Writing only when the
// markup actually differs keeps them one-shot, the way setGoalRing's __ringState cache does for
// the ring. Nothing else writes these hosts, so the cached string stays true to the DOM.
