const SCORING=__SCORING_CONFIG__;
const GRADES=SCORING.grades,CATEGORIES=Object.keys(SCORING.categories),CAT_LABELS=SCORING.categoryLabels,CAT_ICONS=SCORING.categoryIcons;
const DAILY_MAX=CATEGORIES.reduce((sum,c)=>sum+SCORING.categories[c],0)+SCORING.balancedDayBonus;
const BOUNTY_BY_ID=new Map(SCORING.bounties.map(b=>[b.id,b]));
const TYPE_ICONS={climb:CAT_ICONS.climb,exercise:CAT_ICONS.exercise,mobility:CAT_ICONS.mobility,bounty:'🎯'};
const SCRIPT=__APPS_SCRIPT__;
const SUPPORTED_API_VERSIONS=new Set([__API_VERSION__]);
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDateOnly(value){const s=String(value||''),m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s);if(!m)return null;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),12);return localDate(d)===s?d:null}
function weekKey(value){const d=parseDateOnly(String(value||'').slice(0,10));if(!d)return'0000-00-00';d.setDate(d.getDate()-(d.getDay()+6)%7);return localDate(d)}
function dateInTimeZone(date,timeZone){try{const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),get=x=>parts.find(p=>p.type===x)?.value;return`${get('year')}-${get('month')}-${get('day')}`}catch{return''}}
function defaultConfig(){const d=new Date(),end=new Date(d);end.setDate(end.getDate()+69);return{startDate:localDate(d),tripDate:localDate(end),goal:500,crew:[]}}
function safeJson(key,fallback,accept=()=>true){try{const raw=localStorage.getItem(key);if(raw===null)return fallback;const value=JSON.parse(raw);return accept(value)?value:fallback}catch{return fallback}}
function normalizeCrew(value){const seen=new Set();return(Array.isArray(value)?value:[]).map(x=>({name:(typeof x==='string'?x:String(x&&x.name||'')).trim()})).filter(x=>{const key=x.name.toLowerCase();if(!x.name||x.name.length>30||seen.has(key))return false;seen.add(key);return true})}
function parseRemoteConfig(value,remoteErrors){const errors={};for(const item of Array.isArray(remoteErrors)?remoteErrors:[]){if(item&&item.field)errors[item.field+(item.value?'_'+item.value:'')]=`${item.value?item.value+': ':''}${item.reason||'is invalid'}`}if(!value||typeof value!=='object'||Array.isArray(value))return{value:null,errors};const startDate=String(value.startDate||''),tripDate=String(value.tripDate||''),goal=Number(value.goal),crew=normalizeCrew(value.crew);if(!parseDateOnly(startDate))errors.challengeStart='Challenge start must use YYYY-MM-DD.';if(!parseDateOnly(tripDate))errors.tripDate='Challenge end must use YYYY-MM-DD.';if(parseDateOnly(startDate)&&parseDateOnly(tripDate)&&startDate>tripDate)errors.challengeStart='Challenge start must be on or before the end.';if(!Number.isInteger(goal)||goal<50||goal>10000)errors.groupGoal='Group goal must be a whole number from 50 to 10,000.';return{value:Object.keys(errors).some(k=>['challengeStart','tripDate','groupGoal'].includes(k))?null:{startDate,tripDate,goal,crew},errors}}
function sanitizeConfig(value,fallback=defaultConfig()){return parseRemoteConfig(value,[]).value||fallback}
function sanitizeActivities(value){return Array.isArray(value)?value.filter(x=>x&&typeof x==='object'&&!Array.isArray(x)&&['climb','exercise','mobility','bounty'].includes(x.type)):[]}
function bountyById(id){return BOUNTY_BY_ID.get(String(id||''))||null}
function hashText(text){let h=2166136261;const s=String(text);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function dailyBounties(date){const day=String(date||'').slice(0,10);return CATEGORIES.map(cat=>{const pool=SCORING.bounties.filter(b=>b.category===cat);return pool.length?pool[hashText(day+'|'+cat)%pool.length]:null}).filter(Boolean)}
function activityPoints(x){if(!x)return 0;if(x.type==='bounty')return(bountyById(x.bountyId)||{}).points||0;return SCORING.categories[x.type]||0}
const creditKey=(x,i)=>x.id||i;
const nameKey=x=>String(x&&x.name||'').trim().toLowerCase();
function dateInChallenge(date,settings=config){return Boolean(parseDateOnly(date)&&parseDateOnly(settings&&settings.startDate)&&parseDateOnly(settings&&settings.tripDate)&&date>=settings.startDate&&date<=settings.tripDate)}
function computeCredits(entries,settings=config){const info=new Map(),weeks=new Map(),totals=new Map(),dayMeter=new Map(),bountyWeekCount=new Map(),bountyUsed=new Map(),daySeen=new Map(),bonusGiven=new Set(),inWin=[];entries.forEach((x,i)=>{const base=activityPoints(x);if(!dateInChallenge(x.date,settings)){info.set(creditKey(x,i),{base,credit:0,reason:'outside challenge'});return}inWin.push({x,i,base})});inWin.sort((a,b)=>String(a.x.date).localeCompare(String(b.x.date))||String(a.x.createdAt||'').localeCompare(String(b.x.createdAt||''))||String(a.x.id||'').localeCompare(String(b.x.id||''))||a.i-b.i);const addWeek=(nm,wk,p)=>weeks.set(nm+'|'+wk,(weeks.get(nm+'|'+wk)||0)+p),addTotal=(nm,p)=>totals.set(nm,(totals.get(nm)||0)+p),addMeter=(nm,d,p)=>dayMeter.set(nm+'|'+d,Math.min(DAILY_MAX,(dayMeter.get(nm+'|'+d)||0)+p));for(const {x,i,base} of inWin){const nm=nameKey(x),wk=weekKey(x.date),d=String(x.date).slice(0,10),dk=nm+'|'+d;if(x.type==='bounty'){bountyWeekCount.set(nm+'|'+wk,(bountyWeekCount.get(nm+'|'+wk)||0)+1);const used=bountyUsed.get(nm+'|'+wk)||0,credit=Math.max(0,Math.min(base,SCORING.weeklyBountyCap-used));bountyUsed.set(nm+'|'+wk,used+credit);info.set(creditKey(x,i),{base,credit,reason:credit<base?'weekly cap':''});addWeek(nm,wk,credit);addTotal(nm,credit);continue}if(!daySeen.has(dk))daySeen.set(dk,new Set());const seen=daySeen.get(dk);let credit,reason='';if(seen.has(x.type)){credit=0;reason='already logged'}else{credit=base;seen.add(x.type)}info.set(creditKey(x,i),{base,credit,reason});addWeek(nm,wk,credit);addTotal(nm,credit);addMeter(nm,d,credit);if(!bonusGiven.has(dk)&&CATEGORIES.every(c=>seen.has(c))){bonusGiven.add(dk);addWeek(nm,wk,SCORING.balancedDayBonus);addTotal(nm,SCORING.balancedDayBonus);addMeter(nm,d,SCORING.balancedDayBonus)}}return{info,weeks,totals,dayMeter,bountyWeekCount}}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDay(value){const date=String(value||'').slice(0,10),now=challengeToday();if(date===now)return'Today';const prior=parseDateOnly(now);if(prior){prior.setDate(prior.getDate()-1);if(date===localDate(prior))return'Yesterday'}const d=parseDateOnly(date);return d?d.toLocaleDateString('en-US',{month:'short',day:'numeric'}):date}
function meterMarkup(points){const n=Math.max(0,Math.min(DAILY_MAX,Number(points)||0));return Array.from({length:DAILY_MAX},(_,i)=>`<i class="${i<n?'filled':''}"></i>`).join('')}
function cacheKey(kind,url=endpoint){return`roadToSendShared:${kind}:${encodeURIComponent(url)}`}
let endpoint='',incoming,logs=[],config=defaultConfig(),me='',recordingFor='',lastSyncedAt=0,protocolVersion=0,serverDate='',challengeTimeZone='',syncState='local',syncDetail='',syncErrorCode='',configErrors={},requestSerial=0,setupDirty=false;
function loadInitialState(){endpoint=localStorage.getItem('roadToSendEndpoint')||'';incoming=new URLSearchParams(location.search);if(incoming.get('sheet')){endpoint=incoming.get('sheet').trim();localStorage.setItem('roadToSendEndpoint',endpoint)}me=localStorage.getItem('roadToSendMe')||'';if(endpoint){logs=sanitizeActivities(safeJson(cacheKey('activities'),[],Array.isArray));config=sanitizeConfig(safeJson(cacheKey('config'),defaultConfig(),x=>x&&typeof x==='object'));const meta=safeJson(cacheKey('meta'),{},x=>x&&typeof x==='object');lastSyncedAt=Number(meta.lastSyncedAt)||0;protocolVersion=Number(meta.protocolVersion)||0;serverDate=String(meta.serverDate||'');challengeTimeZone=String(meta.timeZone||'');syncState=lastSyncedAt?'stale':'loading'}else{if(localStorage.getItem('roadToSendConfigV9')===null&&localStorage.getItem('roadToSendConfigV8')!==null)localStorage.setItem('roadToSendConfigV9',JSON.stringify(sanitizeConfig(safeJson('roadToSendConfigV8',defaultConfig(),x=>x&&typeof x==='object'))));logs=sanitizeActivities(safeJson('roadToSendLogsV9',[],Array.isArray));config=sanitizeConfig(safeJson('roadToSendConfigV9',defaultConfig(),x=>x&&typeof x==='object'));syncState='local'}recordingFor=me}
function persistShared(){if(!endpoint)return;localStorage.setItem(cacheKey('activities'),JSON.stringify(logs));localStorage.setItem(cacheKey('config'),JSON.stringify(config));localStorage.setItem(cacheKey('meta'),JSON.stringify({lastSyncedAt,protocolVersion,serverDate,timeZone:challengeTimeZone}))}
function persistLocal(){localStorage.setItem('roadToSendLogsV9',JSON.stringify(logs));localStorage.setItem('roadToSendConfigV9',JSON.stringify(config))}
function challengeToday(){return endpoint?(dateInTimeZone(new Date(),challengeTimeZone)||serverDate||localDate()):localDate()}
function participant(name){return config.crew.find(x=>x.name.toLowerCase()===String(name||'').trim().toLowerCase())}
function currentTarget(){return participant(recordingFor)||participant(me)||null}
function totalsModel(){const credits=computeCredits(logs),wk=weekKey(challengeToday()),names=new Map();for(const p of config.crew)names.set(p.name.toLowerCase(),p.name);logs.forEach(x=>{const d=String(x.name||'').trim();if(d&&!names.has(d.toLowerCase()))names.set(d.toLowerCase(),d)});const sorted=[...names.entries()].map(([lower,name])=>({name,total:credits.totals.get(lower)||0,week:credits.weeks.get(lower+'|'+wk)||0,bounties:credits.bountyWeekCount.get(lower+'|'+wk)||0})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));const maxB=Math.max(0,...sorted.map(x=>x.bounties)),hunters=maxB>0?sorted.filter(x=>x.bounties===maxB).map(x=>x.name):[];return Object.assign({},credits,{sorted,total:sorted.reduce((sum,x)=>sum+x.total,0),hunters,huntCount:maxB})}
function setMeter(selector,points,label){const el=document.querySelector(selector);if(!el)return;el.innerHTML=meterMarkup(points);el.setAttribute('aria-label',label)}
function activityMarkup(items,limit,allowDelete){const {info}=computeCredits(logs);return items.map((x,i)=>({x,i:logs.indexOf(x)})).sort((a,b)=>String(b.x.date).localeCompare(String(a.x.date))||String(b.x.createdAt||'').localeCompare(String(a.x.createdAt||''))).slice(0,limit).map(({x,i})=>{const c=info.get(creditKey(x,i))||{base:activityPoints(x),credit:0},title=x.type==='bounty'?(x.bountyTitle||(bountyById(x.bountyId)||{}).title||'Bounty'):CAT_LABELS[x.type]||x.type,detail=x.type==='climb'?`${CAT_LABELS.climb}${x.hardestGrade?' · '+esc(x.hardestGrade):''}`:x.type==='bounty'?`🎯 ${esc(title)}`:`${esc(CAT_LABELS[x.type]||x.type)}${x.note?' · '+esc(x.note):''}`,note={'outside challenge':'outside window','already logged':'already logged today','weekly cap':'weekly bounty cap'}[c.reason]||(c.credit<c.base?`${c.base} generated`:''),score=`<strong>+${c.credit}</strong>${note?`<small>${note}</small>`:''}`,del=allowDelete?`<button class="del" type="button" data-del="${i}"${x.id?` data-id="${esc(x.id)}"`:''} aria-label="Delete ${esc(title)} for ${esc(x.name)}">×</button>`:'';return`<div class="activity"><div class="avatar">${TYPE_ICONS[x.type]||'🧗'}</div><div><strong>${esc(x.name)}</strong><small>${detail} · ${fmtDay(x.date)}</small></div><div class="pts">${score}</div>${del}</div>`}).join('')||'<p class="hint">No activity yet.</p>'}
function renderBounties(){const list=dailyBounties(challengeToday()),card=document.querySelector('#todayBounties');if(card)card.innerHTML=list.map(b=>`<div class="bounty"><div class="bounty-cat" aria-hidden="true">${CAT_ICONS[b.category]}</div><div><strong>${esc(b.title)}</strong><small>${esc(b.description)}</small></div><div class="pts">+${b.points}</div></div>`).join('')||'<p class="hint">No bounties today.</p>'}
function render(){const model=totalsModel(),owner=participant(me);if(me&&!owner){me='';recordingFor='';localStorage.removeItem('roadToSendMe')}document.querySelector('#youGreeting').textContent=owner?`Hi, ${owner.name}`:'Choose your profile';document.querySelector('#changeMeBtn').textContent=owner?'Change me':'Choose me';const today=challengeToday(),meLower=String(me).toLowerCase(),todayPoints=model.dayMeter.get(meLower+'|'+today)||0;document.querySelector('#youTodayPoints').textContent=todayPoints;const todayDone=todayPoints>=DAILY_MAX,todayStatusEl=document.querySelector('#todayStatus');todayStatusEl.textContent=todayDone?'Balanced day':'Ready';todayStatusEl.classList.toggle('max',todayDone);setMeter('#youMeter',todayPoints,`${todayPoints} of ${DAILY_MAX} points today`);const mine=model.sorted.find(x=>x.name.toLowerCase()===meLower),rank=mine?model.sorted.indexOf(mine)+1:0;document.querySelector('#youTotal').textContent=mine?mine.total:0;document.querySelector('#youRank').textContent=rank?`#${rank}`:'—';document.querySelector('#personalActivity').innerHTML=activityMarkup(logs.filter(x=>x.name.toLowerCase()===meLower),5,false);renderBounties();const target=currentTarget();document.querySelector('#recordingName').textContent=target?target.name:'Choose a person';document.querySelector('#totalPoints').textContent=model.total;document.querySelector('#groupGoal').textContent=config.goal;const pctRaw=Math.round(model.total/config.goal*100),pct=Math.min(100,pctRaw),groupPercentEl=document.querySelector('#groupPercent');groupPercentEl.textContent=pctRaw+'%';groupPercentEl.classList.toggle('reached',pctRaw>=100);document.querySelector('#groupProgress').style.width=pct+'%';const hunter=document.querySelector('#bountyHunter');if(hunter)hunter.innerHTML=model.huntCount>0?`🏹 <strong>Bounty Hunter${model.hunters.length>1?'s':''} of the week:</strong> ${model.hunters.map(esc).join(', ')} · ${model.huntCount} bount${model.huntCount===1?'y':'ies'} claimed`:'<span class="hint">Claim the most bounties this week to earn the 🏹 badge.</span>';document.querySelector('#leaderRows').innerHTML=model.sorted.map((x,i)=>`<tr${x.name.toLowerCase()===meLower?' class="me"':''}><td class="rank">#${i+1}</td><td><strong>${esc(x.name)}</strong>${model.hunters.includes(x.name)?' <span class="hunter" title="Bounty Hunter of the week">🏹</span>':''}</td><td>${x.week}</td><td><strong>${x.total}</strong></td></tr>`).join('')||'<tr><td colspan="4">Create a profile to join the crew.</td></tr>';document.querySelector('#activityList').innerHTML=activityMarkup(logs,20,true);const messages=Object.values(configErrors),notice=document.querySelector('#configNotice');notice.classList.toggle('hide',!messages.length);notice.textContent=messages.length?`Setup needs attention: ${messages.join(' ')}`:'';renderSync();updateRecordPreview()}
function showTab(name){document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.bottom-nav [data-tab]').forEach(x=>{const active=x.dataset.tab===name;x.classList.toggle('active',active);active?x.setAttribute('aria-current','page'):x.removeAttribute('aria-current')});history.replaceState(null,'','#'+name);if(name==='record'&&!currentTarget())openIdentity(false);window.scrollTo(0,0);updateRecordPreview()}
let lastFocused=null;
function focusableIn(container){return[...container.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null)}
function openModal(id){lastFocused=document.activeElement;const m=document.querySelector('#'+id);m.classList.add('open');m.__trap=event=>{if(event.key!=='Tab')return;const items=focusableIn(m);if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};m.addEventListener('keydown',m.__trap)}
function closeModal(id){const m=document.querySelector('#'+id);m.classList.remove('open');if(m.__trap){m.removeEventListener('keydown',m.__trap);m.__trap=null}if(lastFocused&&typeof lastFocused.focus==='function'){lastFocused.focus()}lastFocused=null}
function crewOptions(){return config.crew.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')}
function openIdentity(canClose=true){const select=document.querySelector('#identityMember');select.innerHTML='<option value="">Choose a person</option>'+crewOptions();select.value=participant(me)?participant(me).name:'';document.querySelector('#identityClose').classList.toggle('hide',!canClose&&!participant(me));document.querySelector('#newParticipantName').value='';document.querySelector('#createProfileError').classList.add('hide');openModal('identityModal');(config.crew.length?select:document.querySelector('#newParticipantName')).focus()}
function openProxy(){const select=document.querySelector('#proxyMember');select.innerHTML=crewOptions();select.value=currentTarget()?.name||'';openModal('proxyModal');select.focus()}
function saveIdentity(){const p=participant(document.querySelector('#identityMember').value);if(!p)return toast('Choose a crew member.');me=p.name;recordingFor=me;localStorage.setItem('roadToSendMe',me);closeModal('identityModal');render()}
async function createProfile(){const name=document.querySelector('#newParticipantName').value.trim(),error=document.querySelector('#createProfileError'),button=document.querySelector('#createProfile');error.classList.add('hide');if(!name||name.length>30){error.textContent='Enter a name from 1 to 30 characters.';error.classList.remove('hide');return}if(participant(name)){error.textContent='That name already exists. Choose it above instead.';error.classList.remove('hide');return}button.disabled=true;button.textContent='Creating…';try{let person;if(endpoint){const response=await fetchShared(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'addParticipant',name})}),saved=await response.json();if(!response.ok||!saved.ok)throw Error(saved?.error?.message||'The Sheet rejected this profile.');config=sanitizeConfig(saved.config,config);person=participant(saved.participant?.name||name);await loadRemote()}else{person={name};config=Object.assign({},config,{crew:[...config.crew,person]});persistLocal()}if(!person)throw Error('Profile was not returned.');me=person.name;recordingFor=me;localStorage.setItem('roadToSendMe',me);closeModal('identityModal');render();toast(`Welcome, ${person.name}!`)}catch(reason){error.textContent=reason.message||'Profile could not be created.';error.classList.remove('hide')}finally{button.disabled=false;button.textContent='Create my profile'}}
function saveProxy(){const p=participant(document.querySelector('#proxyMember').value);if(!p)return toast('Choose a crew member.');recordingFor=p.name;closeModal('proxyModal');render()}
function selectedType(){return document.querySelector('input[name="activityType"]:checked')?.value||'climb'}
function recordDate(){return document.querySelector('#activityDate').value||challengeToday()}
function noteValue(){return(document.querySelector('#activityNote')?.value||'').trim().slice(0,120)}
function draftActivity(){const target=currentTarget(),type=selectedType(),base={name:target?.name||'',type,date:recordDate(),createdAt:new Date().toISOString(),id:'__preview__'};if(type==='climb')base.hardestGrade=document.querySelector('#hardestGrade').value;else if(type==='bounty'){const b=bountyById(document.querySelector('#bountySelect').value);base.bountyId=b?b.id:'';base.bountyTitle=b?b.title:'';base.category=b?b.category:'';base.note=noteValue()}else base.note=noteValue();return base}
function populateBountySelect(){const select=document.querySelector('#bountySelect');if(!select)return;const list=dailyBounties(recordDate()),prev=select.value;select.innerHTML='<option value="">Choose a bounty</option>'+list.map(b=>`<option value="${esc(b.id)}">${CAT_ICONS[b.category]} ${esc(b.title)} · +${b.points}</option>`).join('');select.value=list.some(b=>b.id===prev)?prev:''}
function updateRecordPreview(){if(typeof document==='undefined')return;const type=selectedType(),climb=document.querySelector('#climbFields'),note=document.querySelector('#noteFields'),bounty=document.querySelector('#bountyFields');if(!climb||!note||!bounty)return;climb.classList.toggle('hide',type!=='climb');note.classList.toggle('hide',type==='climb');bounty.classList.toggle('hide',type!=='bounty');if(type==='bounty')populateBountySelect();const target=currentTarget(),draft=draftActivity(),base=activityPoints(draft),result=computeCredits([...logs,draft]),preview=result.info.get('__preview__')||{credit:0,base,reason:''},credit=preview.credit,meterAfter=result.dayMeter.get(String(draft.name).toLowerCase()+'|'+draft.date)||0;document.querySelector('#rawPreview').textContent=base;let msg;if(type==='bounty')msg=!draft.bountyId?'Choose one of today’s bounties.':credit<base?'Weekly bounty cap reached · bragging rights only':`Bounty! +${credit} toward your week`;else if(preview.reason==='already logged')msg=`${CAT_LABELS[type]} already logged today · earns 0 more`;else msg=`Counts in full · +${credit} today`;document.querySelector('#creditPreview').textContent=msg;setMeter('#recordMeter',meterAfter,`${meterAfter} of ${DAILY_MAX} points after this activity`);document.querySelector('#saveActivityBtn').disabled=!target||!dateInChallenge(draft.date)||(type==='bounty'&&!draft.bountyId)}
function setDefaultRecordDate(){const field=document.querySelector('#activityDate'),now=challengeToday();field.min=config.startDate;field.max=config.tripDate;field.value=now<config.startDate?config.startDate:now>config.tripDate?config.tripDate:now}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
function syncFailureCode(error){return error&&error.message==='version'?'RTS-REFRESH-VERSION':error&&error.message==='json'?'RTS-REFRESH-DATA':'RTS-REFRESH-NETWORK'}
async function fetchShared(url,options={}){const target=new URL(url);target.searchParams.set('_',Date.now().toString());return fetch(target.toString(),Object.assign({cache:'no-store'},options))}
function unpackRemote(result){if(Array.isArray(result))throw Error('version');if(!result||!Array.isArray(result.activities))throw Error('json');const version=Number(result.version);if(!SUPPORTED_API_VERSIONS.has(version))throw Error('version');const parsed=parseRemoteConfig(result.config,result.configErrors);return{version,features:Array.isArray(result.features)?result.features.map(String):[],activities:sanitizeActivities(result.activities),config:parsed.value,configErrors:parsed.errors,serverDate:String(result.serverDate||''),timeZone:String(result.timeZone||'')}}
async function loadRemote(force=false){if(!endpoint)return false;const serial=++requestSerial;syncState='loading';syncDetail='';renderSync();try{const response=await fetchShared(endpoint);if(!response.ok)throw Error('network');const remote=unpackRemote(await response.json());if(serial!==requestSerial)return false;logs=remote.activities;if(remote.config)config=remote.config;configErrors=remote.configErrors;protocolVersion=remote.version;serverDate=remote.serverDate;challengeTimeZone=remote.timeZone;lastSyncedAt=Date.now();syncState='live';syncErrorCode='';persistShared();setDefaultRecordDate();render();if(!participant(me))openIdentity(false);return true}catch(error){if(serial!==requestSerial)return false;syncState=lastSyncedAt?'stale':'error';syncErrorCode=syncFailureCode(error);syncDetail=error.message==='version'?'Apps Script update required':'Could not reach the Sheet';renderSync();if(force)toast(syncDetail);return false}}
function renderSync(){if(typeof document==='undefined')return;const el=document.querySelector('#syncStatus');if(!el)return;if(!endpoint){el.textContent='Local mode';el.disabled=true;document.querySelector('#diagnosticTitle').textContent='Local mode';document.querySelector('#diagnosticDetail').textContent='Entries stay in this browser.';return}el.disabled=false;const age=lastSyncedAt?Math.floor((Date.now()-lastSyncedAt)/60000):null,when=age===null?'never':age<1?'just now':`${age}m ago`;el.textContent=syncState==='loading'?'Syncing…':syncState==='live'?`Live · ${when} · ↻`:syncState==='stale'?`Cached · retry ↻`:'Sync failed · retry ↻';document.querySelector('#diagnosticTitle').textContent=syncState==='live'?'Shared Sheet connected':syncDetail||'Using cached data';document.querySelector('#diagnosticDetail').textContent=`Protocol ${protocolVersion?'v'+protocolVersion:'not confirmed'} · Last successful sync: ${lastSyncedAt?new Date(lastSyncedAt).toLocaleString():'never'}.`;const code=document.querySelector('#diagnosticCode');code.classList.toggle('hide',!syncErrorCode);code.textContent=syncErrorCode}
async function submitActivity(event){event.preventDefault();const target=currentTarget(),draft=draftActivity(),type=draft.type;if(!target)return openIdentity(false);if(!dateInChallenge(draft.date))return toast(`Choose a date from ${config.startDate} through ${config.tripDate}.`);if(type==='bounty'){if(!draft.bountyId)return toast('Choose one of today’s bounties.');if(!dailyBounties(draft.date).some(b=>b.id===draft.bountyId))return toast('That bounty is not available on that date.')}const button=document.querySelector('#saveActivityBtn');button.disabled=true;button.textContent='Saving…';let refreshFailed=false;try{if(endpoint){const response=await fetchShared(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({name:draft.name,type:draft.type,date:draft.date,hardestGrade:draft.hardestGrade||'',note:draft.note||'',bountyId:draft.bountyId||''})});if(!response.ok)throw Error('Request failed.');const saved=await response.json();if(!saved||saved.ok!==true)throw Error(saved?.error?.message||'The Sheet rejected this entry.');refreshFailed=!(await loadRemote())}else{draft.id=`local-${Date.now()}`;draft.points=activityPoints(draft);draft.category=type==='bounty'?draft.category:type;logs.push(draft);persistLocal()}recordingFor=me;const noteField=document.querySelector('#activityNote');if(noteField)noteField.value='';const bountyField=document.querySelector('#bountySelect');if(bountyField)bountyField.value='';setDefaultRecordDate();document.querySelector('#dateFields').classList.add('hide');const dateToggleEl=document.querySelector('#dateToggle');dateToggleEl.setAttribute('aria-expanded','false');dateToggleEl.textContent='＋ Different day';render();showTab('you');const savedForOther=String(draft.name).toLowerCase()!==String(me).toLowerCase();toast(refreshFailed?'Saved to the Sheet, but refresh failed. Do not retry the save; select sync to refresh.':savedForOther?`Saved for ${draft.name}.`:'Activity saved.')}catch(error){toast(`Save failed—${error.message||'the entry was not added.'} It is safe to retry.`)}finally{button.disabled=false;button.textContent='Save activity';updateRecordPreview()}}
async function deleteEntry(index,id){const item=logs[index];if(!item)return;const what=item.type==='bounty'?(item.bountyTitle||'bounty'):`${CAT_LABELS[item.type]||item.type}${item.hardestGrade?' '+item.hardestGrade:''}`;if(!confirm(`Delete ${what} for ${item.name}?`))return;if(endpoint){try{const response=await fetchShared(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'delete',id})}),result=await response.json();if(!response.ok||!result.ok)throw Error(result?.error?.message||'Delete rejected.');await loadRemote(true);toast('Entry deleted.')}catch(error){toast(`Delete failed — ${error.message}`)}}else{logs.splice(index,1);persistLocal();render();toast('Entry deleted.')}}
function addParticipantRow(person={name:''}){const el=document.querySelector('#participantRows'),index=el.children.length;el.insertAdjacentHTML('beforeend',`<div class="participant-row"><input aria-label="Participant ${index+1} name" class="participant-name" maxlength="30" placeholder="Name" value="${esc(person.name)}" /><button class="icon-btn remove-participant" type="button" aria-label="Remove ${esc(person.name||'participant')}">×</button></div>`)}
function populateSetup(){document.querySelector('#endpoint').value=endpoint;document.querySelector('#challengeStart').value=config.startDate;document.querySelector('#tripDate').value=config.tripDate;document.querySelector('#groupGoalInput').value=config.goal;const rows=document.querySelector('#participantRows');rows.innerHTML='';config.crew.forEach(addParticipantRow);if(!config.crew.length)addParticipantRow();document.querySelector('#scriptCode').textContent=SCRIPT;setupDirty=false}
function openSetup(){populateSetup();openModal('setupModal');document.querySelector('#endpoint').focus()}
function readSetupConfig(){const crew=[...document.querySelectorAll('.participant-row')].map(row=>({name:row.querySelector('.participant-name').value.trim()})).filter(x=>x.name);return{startDate:document.querySelector('#challengeStart').value,tripDate:document.querySelector('#tripDate').value,goal:Number(document.querySelector('#groupGoalInput').value),crew}}
function validateSetup(value){const parsed=parseRemoteConfig(value,[]),errors=Object.assign({},parsed.errors);if(!value.crew.length)errors.crew='Add at least one participant.';return{value:parsed.value,errors}}
async function testConnection(){const url=document.querySelector('#endpoint').value.trim(),result=document.querySelector('#testResult');result.textContent='Testing…';try{const response=await fetchShared(url),remote=unpackRemote(await response.json());result.textContent=`Connected — API v${remote.version}`;return true}catch(error){result.textContent=error.message==='version'?'Outdated Apps Script — deploy v9':'Connection failed';return false}}
async function saveSetup(){const candidate=readSetupConfig(),check=validateSetup(candidate),errors=document.querySelector('#setupErrors'),url=document.querySelector('#endpoint').value.trim();if(Object.keys(check.errors).length){errors.textContent=Object.values(check.errors).join(' ');errors.classList.remove('hide');return}errors.classList.add('hide');const button=document.querySelector('#saveSetupBtn');button.disabled=true;button.textContent='Saving…';try{if(url){const response=await fetchShared(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'saveConfig',config:candidate})}),saved=await response.json();if(!response.ok||!saved.ok)throw Error(saved?.error?.message||'The Sheet rejected setup.');endpoint=url;localStorage.setItem('roadToSendEndpoint',endpoint);config=sanitizeConfig(saved.config,candidate);configErrors={};lastSyncedAt=Date.now();protocolVersion=[...SUPPORTED_API_VERSIONS][0];await loadRemote()}else{config=candidate;configErrors={};persistLocal();render()}closeModal('setupModal');await copyCrewLink();if(!participant(me))openIdentity(false);toast(url?'Shared setup saved. Crew link copied.':'Local setup saved.')}catch(error){errors.textContent=error.message||'Setup could not be saved.';errors.classList.remove('hide')}finally{button.disabled=false;button.textContent='Save centrally & copy crew link'}}
async function copyCrewLink(){const url=new URL(location.href);url.hash='';if(endpoint)url.searchParams.set('sheet',endpoint);else url.searchParams.delete('sheet');await navigator.clipboard.writeText(url.toString());toast('Crew link copied.')}
function copyScript(){navigator.clipboard.writeText(SCRIPT).then(()=>toast('Apps Script copied.'))}
function exportData(){const blob=new Blob([JSON.stringify({version:[...SUPPORTED_API_VERSIONS][0],exportedAt:new Date().toISOString(),mode:endpoint?'shared-cache':'local',config,activities:logs},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='road-to-send-export.json';a.click();URL.revokeObjectURL(a.href)}
function disconnect(){if(!confirm('Switch this device to local mode? Shared Sheet data will remain untouched.'))return;localStorage.removeItem('roadToSendEndpoint');endpoint='';logs=sanitizeActivities(safeJson('roadToSendLogsV9',[],Array.isArray));config=sanitizeConfig(safeJson('roadToSendConfigV9',defaultConfig(),x=>x&&typeof x==='object'));syncState='local';configErrors={};closeModal('setupModal');setDefaultRecordDate();render();toast('Using local mode.')}
function init(){loadInitialState();document.querySelector('#hardestGrade').innerHTML='<option value="">Grade (optional)</option>'+GRADES.map(x=>`<option value="${x}">${x}</option>`).join('');setDefaultRecordDate();document.querySelectorAll('[data-tab]').forEach(x=>x.addEventListener('click',event=>{event.preventDefault();showTab(x.dataset.tab)}));document.querySelectorAll('input[name="activityType"]').forEach(x=>x.addEventListener('change',updateRecordPreview));document.querySelector('#hardestGrade').addEventListener('change',updateRecordPreview);const noteField=document.querySelector('#activityNote');if(noteField)noteField.addEventListener('input',updateRecordPreview);const bountySelect=document.querySelector('#bountySelect');if(bountySelect)bountySelect.addEventListener('change',updateRecordPreview);document.querySelector('#activityDate').addEventListener('change',updateRecordPreview);document.querySelector('#dateToggle').addEventListener('click',()=>{const box=document.querySelector('#dateFields'),toggle=document.querySelector('#dateToggle'),open=box.classList.toggle('hide')===false;toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'－ Use today instead':'＋ Different day';if(open)document.querySelector('#activityDate').focus();else{setDefaultRecordDate();updateRecordPreview()}});document.querySelector('#recordForm').addEventListener('submit',submitActivity);document.querySelector('#saveIdentity').addEventListener('click',saveIdentity);document.querySelector('#createProfile').addEventListener('click',createProfile);document.querySelector('#identityClose').addEventListener('click',()=>closeModal('identityModal'));document.querySelector('#saveProxy').addEventListener('click',saveProxy);document.querySelector('#syncStatus').addEventListener('click',()=>loadRemote(true));document.querySelector('#diagnosticCode').addEventListener('click',()=>navigator.clipboard.writeText(syncErrorCode).then(()=>toast('Diagnostic code copied.')));document.querySelector('#addParticipant').addEventListener('click',()=>addParticipantRow());document.querySelector('#participantRows').addEventListener('click',event=>{const button=event.target.closest('.remove-participant');if(button)button.closest('.participant-row').remove()});document.querySelector('#activityList').addEventListener('click',event=>{const button=event.target.closest('[data-del]');if(button)deleteEntry(Number(button.dataset.del),button.dataset.id)});document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.modal.open').forEach(x=>closeModal(x.id))});const start=location.hash.slice(1);showTab(['you','record','crew'].includes(start)?start:'you');render();if(endpoint)loadRemote();else if(!participant(me))openIdentity(false)}
if(typeof document!=='undefined')init();
