const SCORING=__SCORING_CONFIG__;
const API_VERSION=__API_VERSION__;
const FEATURES=['daily-cap-v1','participant-pull-mode','challenge-window','self-registration-v1'];
const TABS={activities:'Activities',settings:'Settings',participants:'Participants',benchmarks:'Benchmarks'};
const ACTIVITY_HEADERS=['id','name','type','points','date','createdAt','hardestGrade','pullUps','pullMode'];
const PARTICIPANT_HEADERS=['name','pullMode'];
const DAILY_CAP=SCORING.dailyCap,GRADES=SCORING.grades;
const MONTHS={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};
function tab(name){const s=SpreadsheetApp.getActive();return s.getSheetByName(name)||s.insertSheet(name)}
function normalizeKey(v){return String(v==null?'':v).trim().toLowerCase().replace(/[\s_-]+/g,'')}
function archiveSheet(sheet,label){if(!sheet)return;const stamp=Utilities.formatDate(new Date(),sheetTimeZone(),'yyyyMMdd-HHmmss');sheet.setName(label+' Archive '+stamp)}
function ensureHeaders(sheet,headers){if(sheet.getLastRow()===0)sheet.appendRow(headers);const current=sheet.getRange(1,1,1,Math.max(1,sheet.getLastColumn())).getValues()[0],seen={};current.forEach(x=>seen[normalizeKey(x)]=true);headers.forEach(h=>{if(!seen[normalizeKey(h)]){sheet.getRange(1,sheet.getLastColumn()+1).setValue(h);seen[normalizeKey(h)]=true}})}
function setup(){const book=SpreadsheetApp.getActive(),props=PropertiesService.getDocumentProperties(),schema=props.getProperty('roadToSendSchema');if(schema!=='7'&&schema!=='8'){archiveSheet(book.getSheetByName(TABS.activities),'Activities');archiveSheet(book.getSheetByName(TABS.benchmarks),'Benchmarks')}props.setProperty('roadToSendSchema','8');const a=tab(TABS.activities),s=tab(TABS.settings),p=tab(TABS.participants);ensureHeaders(a,ACTIVITY_HEADERS);ensureHeaders(p,PARTICIPANT_HEADERS);if(s.getLastRow()===0)s.appendRow(['key','value']);formatSheets(a,s,p)}
function formatSheets(a,s,p){[a,s,p].forEach(x=>{x.setFrozenRows(1);x.getRange(1,1,1,x.getLastColumn()).setFontWeight('bold').setBackground('#e8efe7')});s.getRange('A2').setNote('Required key: challengeStart.');s.getRange('A3').setNote('Required key: tripDate. Inclusive final day.');s.getRange('A4').setNote('Required key: groupGoal.');s.getRange('B2:B3').setNumberFormat('yyyy-mm-dd').setDataValidation(SpreadsheetApp.newDataValidation().requireDate().setAllowInvalid(true).build());s.getRange('B4').setNumberFormat('0').setDataValidation(SpreadsheetApp.newDataValidation().requireNumberBetween(50,10000).setAllowInvalid(false).build());p.getRange(1,1,p.getMaxRows(),p.getLastColumn()).setNumberFormat('@');const pHeaders=p.getRange(1,1,1,p.getLastColumn()).getValues()[0],modeCol=pHeaders.findIndex(x=>normalizeKey(x)==='pullmode')+1,pRule=SpreadsheetApp.newDataValidation().requireValueInList(['hard','super-hard'],true).setAllowInvalid(false).build();if(modeCol)p.getRange(2,modeCol,Math.max(1,p.getMaxRows()-1),1).setDataValidation(pRule);const headers=a.getRange(1,1,1,a.getLastColumn()).getValues()[0],dateCol=headers.findIndex(x=>normalizeKey(x)==='date')+1;if(dateCol)a.getRange(1,dateCol,a.getMaxRows(),1).setNumberFormat('yyyy-mm-dd')}
function calendarDate(y,m,d){y=Number(y);m=Number(m);d=Number(d);if(!Number.isInteger(y)||!Number.isInteger(m)||!Number.isInteger(d)||y<1900||y>2200)return null;const x=new Date(Date.UTC(y,m-1,d));if(x.getUTCFullYear()!==y||x.getUTCMonth()+1!==m||x.getUTCDate()!==d)return null;return String(y).padStart(4,'0')+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0')}
function parseDateValue(v){if(v instanceof Date){if(isNaN(v.getTime()))return{error:'is not a valid date'};return{value:Utilities.formatDate(v,sheetTimeZone(),'yyyy-MM-dd')}}const text=String(v==null?'':v).trim();if(!text)return{error:'is required'};let m=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m){const value=calendarDate(m[1],m[2],m[3]);return value?{value}:{error:'must be a real calendar date'}}m=text.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m){const value=calendarDate(m[3],m[1],m[2]);return value?{value}:{error:'must be a real calendar date'}}m=text.match(/^([A-Za-z]+)\s+(\d{1,2})(?:,)?\s+(\d{4})$/);if(m&&MONTHS[m[1].slice(0,3).toLowerCase()]){const value=calendarDate(m[3],MONTHS[m[1].slice(0,3).toLowerCase()],m[2]);return value?{value}:{error:'must be a real calendar date'}}return{error:'must use YYYY-MM-DD, MM/DD/YYYY, or a named month'}}
function parseGoal(v){const text=String(v==null?'':v).trim().replace(/,/g,'');if(!text)return{error:'is required'};const value=Number(text);if(!Number.isFinite(value)||!Number.isInteger(value))return{error:'must be a whole number'};if(value<50||value>10000)return{error:'must be from 50 to 10,000'};return{value}}
function normalizePullMode(value){const mode=String(value||'').trim().toLowerCase();return mode==='super-hard'||mode==='men'?'super-hard':mode==='hard'||mode==='women'?'hard':null}
function pullPoints(count,mode){const n=Number(count),bands=SCORING.pullThresholds[normalizePullMode(mode)];if(!Number.isInteger(n)||n<0||!bands)return 0;return bands.reduce((score,band)=>n>=band[0]?band[1]:score,0)}
function participantRecords(){const values=tab(TABS.participants).getDataRange().getValues();if(!values.length)return[];const headers=values.shift().map(normalizeKey),nameCol=headers.indexOf('name'),modeCol=headers.indexOf('pullmode'),legacyCol=headers.indexOf('pullcategory'),seen={};return values.map(r=>({name:String(r[nameCol]||'').trim(),pullMode:normalizePullMode(r[modeCol]||r[legacyCol])})).filter(x=>x.name&&!seen[x.name.toLowerCase()]&&(seen[x.name.toLowerCase()]=true))}
function configError(field,value,reason,cell){return{field,cell:cell||'Settings',value:String(value==null?'':value),reason}}
function readConfig(){const values=tab(TABS.settings).getDataRange().getValues().slice(1),settings={};values.forEach(r=>{const k=normalizeKey(r[0]);if(k)settings[k]=r[1]});const hasStart=Object.prototype.hasOwnProperty.call(settings,'challengestart'),hasTrip=Object.prototype.hasOwnProperty.call(settings,'tripdate'),hasGoal=Object.prototype.hasOwnProperty.call(settings,'groupgoal');if(!hasStart&&!hasTrip&&!hasGoal)return{config:null,errors:[]};const start=parseDateValue(hasStart?settings.challengestart:''),trip=parseDateValue(hasTrip?settings.tripdate:''),goal=parseGoal(hasGoal?settings.groupgoal:''),crew=participantRecords(),errors=[];if(start.error)errors.push(configError('challengeStart',settings.challengestart,start.error,'Settings!B2'));if(trip.error)errors.push(configError('tripDate',settings.tripdate,trip.error,'Settings!B3'));if(start.value&&trip.value&&start.value>trip.value)errors.push(configError('challengeStart',start.value,'must be on or before the challenge end','Settings!B2'));if(goal.error)errors.push(configError('groupGoal',settings.groupgoal,goal.error,'Settings!B4'));crew.forEach((x,i)=>{if(!x.pullMode)errors.push(configError('pullMode',x.name,'must be hard or super-hard','Participants row '+(i+2)))});return{config:start.value&&trip.value&&goal.value?{startDate:start.value,tripDate:trip.value,goal:goal.value,crew}:null,errors}}
function normalizeCrew(value,allowMissing){const seen={};return(Array.isArray(value)?value:[]).map(x=>({name:String(x&&x.name||'').trim(),pullMode:normalizePullMode(x&&(x.pullMode||x.pullCategory))})).filter(x=>x.name&&!seen[x.name.toLowerCase()]&&(seen[x.name.toLowerCase()]=true)).map(x=>{if(!allowMissing&&!x.pullMode)apiError('invalid_config','Every participant needs a pull-up mode',[{field:'pullMode',reason:'must be hard or super-hard',value:x.name}]);if(x.name.length>30)apiError('invalid_config','Participant names must be 30 characters or fewer',[{field:'crew',reason:'name is too long'}]);return x})}
function writeConfig(c){const start=parseDateValue(c&&c.startDate),trip=parseDateValue(c&&c.tripDate),goal=parseGoal(c&&c.goal),errors=[];if(start.error)errors.push(configError('challengeStart',c&&c.startDate,start.error));if(trip.error)errors.push(configError('tripDate',c&&c.tripDate,trip.error));if(start.value&&trip.value&&start.value>trip.value)errors.push(configError('challengeStart',start.value,'must be on or before the challenge end'));if(goal.error)errors.push(configError('groupGoal',c&&c.goal,goal.error));if(errors.length)apiError('invalid_config','Invalid challenge settings',errors);const crew=normalizeCrew(c&&c.crew,false);if(!crew.length)apiError('invalid_config','Add at least one participant',[{field:'crew',reason:'is required'}]);const s=tab(TABS.settings),p=tab(TABS.participants);s.getRange(1,1,Math.max(4,s.getLastRow()),2).clearContent();s.getRange(1,1,4,2).setValues([['key','value'],['challengeStart',start.value],['tripDate',trip.value],['groupGoal',goal.value]]);p.clearContents();p.getRange(1,1,1,2).setValues([PARTICIPANT_HEADERS]);p.getRange(2,1,crew.length,2).setValues(crew.map(x=>[x.name,x.pullMode]));formatSheets(tab(TABS.activities),s,p);return{startDate:start.value,tripDate:trip.value,goal:goal.value,crew}}
function addParticipant(name,pullMode){const current=readConfig();if(!current.config)apiError('setup_required','Challenge setup must be completed before profiles can be created');const person=normalizeCrew([{name,pullMode}],false)[0];if(!person)apiError('invalid_participant','Enter a name',[{field:'name',reason:'is required'}]);if(current.config.crew.some(x=>x.name.toLowerCase()===person.name.toLowerCase()))apiError('duplicate_participant','That name already exists',[{field:'name',reason:'must be unique'}]);const config=writeConfig(Object.assign({},current.config,{crew:current.config.crew.concat([person])}));return{participant:person,config}}
function normalizeActivityRow(row,headers){const byKey={};headers.forEach((k,i)=>byKey[normalizeKey(k)]=row[i]);const item={};ACTIVITY_HEADERS.forEach(k=>item[k]=byKey[normalizeKey(k)]==null?'':byKey[normalizeKey(k)]);if(item.type==='pull')item.pullMode=normalizePullMode(item.pullMode||byKey.pullcategory)||'';const parsed=parseDateValue(item.date);if(parsed.value)item.date=parsed.value;if(item.pullUps!=='')item.pullUps=Number(item.pullUps);item.points=Number(item.points)||0;return item}
function rows(){const values=tab(TABS.activities).getDataRange().getValues();if(!values.length)return[];const headers=values.shift();return values.filter(r=>r.some(c=>c!=='' )).map(r=>normalizeActivityRow(r,headers))}
function appendActivity(item){const a=tab(TABS.activities),headers=a.getRange(1,1,1,a.getLastColumn()).getValues()[0];a.appendRow(headers.map(h=>{const key=ACTIVITY_HEADERS.find(k=>normalizeKey(k)===normalizeKey(h));return item[key]==null?'':item[key]}));return item}
function apiError(code,message,details){const e=new Error(message);e.code=code;e.details=details||[];throw e}
function canonicalParticipant(name){const text=String(name==null?'':name).trim(),match=participantRecords().find(x=>x.name.toLowerCase()===text.toLowerCase());if(!text||!match)apiError('invalid_activity','Choose a participant from the Participants tab',[{field:'name',reason:'must match a participant'}]);return match}
function validateActivity(d){const participant=canonicalParticipant(d&&d.name),type=String(d&&d.type||''),date=parseDateValue(d&&d.date),hardestGrade=String(d&&d.hardestGrade||''),pullUps=Number(d&&d.pullUps),errors=[];if(!['climb','pull'].includes(type))errors.push({field:'type',reason:'must be climb or pull'});if(date.error)errors.push({field:'date',reason:date.error});if(type==='climb'&&!GRADES.includes(hardestGrade))errors.push({field:'hardestGrade',reason:'must be V0 through V17'});if(type==='pull'&&(!Number.isInteger(pullUps)||pullUps<0))errors.push({field:'pullUps',reason:'must be a nonnegative whole number'});if(type==='pull'&&!participant.pullMode)errors.push({field:'pullMode',reason:'must be configured for this participant'});if(errors.length)apiError('invalid_activity','Invalid activity',errors);return{name:participant.name,type,points:type==='climb'?SCORING.climbPoints:pullPoints(pullUps,participant.pullMode),date:date.value,hardestGrade:type==='climb'?hardestGrade:'',pullUps:type==='pull'?pullUps:'',pullMode:type==='pull'?participant.pullMode:''}}
function validateActivityWindow(activity){const c=readConfig().config;if(c&&(activity.date<c.startDate||activity.date>c.tripDate))apiError('outside_challenge_window','Activity date must be from '+c.startDate+' through '+c.tripDate+' (inclusive)',[{field:'date',reason:'is outside the challenge window'}]);return activity}
function activityBasePoints(x){if(x.type==='climb')return GRADES.includes(String(x.hardestGrade))?SCORING.climbPoints:0;if(x.type==='pull')return pullPoints(Number(x.pullUps),x.pullMode||x.pullCategory);return 0}
function dailyCreditInfo(entries){const sorted=entries.map((x,i)=>({x,i})).sort((a,b)=>String(a.x.date).localeCompare(String(b.x.date))||String(a.x.createdAt||'').localeCompare(String(b.x.createdAt||''))||String(a.x.id||'').localeCompare(String(b.x.id||''))||a.i-b.i),used={},credit={};sorted.forEach(({x,i})=>{const key=String(x.name||'').trim().toLowerCase()+'|'+x.date,base=activityBasePoints(x),value=Math.max(0,Math.min(base,DAILY_CAP-(used[key]||0)));used[key]=(used[key]||0)+value;credit[String(x.id||i)]={base,credit:value}});return credit}
function deleteActivity(id){const a=tab(TABS.activities),values=a.getDataRange().getValues();if(!values.length)return false;const headers=values[0],idCol=headers.findIndex(x=>normalizeKey(x)==='id'),rowIndex=values.slice(1).findIndex(r=>String(r[idCol])===id);if(rowIndex<0)return false;a.deleteRow(rowIndex+2);return true}
function sheetTimeZone(){return SpreadsheetApp.getActive().getSpreadsheetTimeZone()||'UTC'}
function sheetToday(){return Utilities.formatDate(new Date(),sheetTimeZone(),'yyyy-MM-dd')}
function doGet(){setup();const c=readConfig();return out({version:API_VERSION,features:FEATURES,activities:rows(),config:c.config,configErrors:c.errors,serverDate:sheetToday(),timeZone:sheetTimeZone(),fetchedAt:new Date().toISOString()})}
function doPost(e){let lock,locked=false;try{let d;try{d=JSON.parse(e&&e.postData&&e.postData.contents||'')}catch(parseError){apiError('invalid_json','Request body must be valid JSON')}if(!d||typeof d!=='object'||Array.isArray(d))apiError('invalid_request','Request body must be a JSON object');lock=LockService.getDocumentLock();lock.waitLock(10000);locked=true;setup();if(d.action==='saveConfig')return out({version:API_VERSION,features:FEATURES,ok:true,config:writeConfig(d.config||{}),configErrors:[]});if(d.action==='addParticipant'){const added=addParticipant(d.name,d.pullMode);return out({version:API_VERSION,features:FEATURES,ok:true,participant:added.participant,config:added.config,configErrors:[]})}if(d.action==='delete'){const id=String(d.id==null?'':d.id).trim();if(!id)apiError('invalid_delete','An activity id is required',[{field:'id',reason:'is required'}]);return deleteActivity(id)?out({version:API_VERSION,ok:true,deleted:id}):out({version:API_VERSION,ok:false,error:{code:'not_found',message:'Activity not found'}})}if(d.action)apiError('unknown_action','Unsupported action: '+String(d.action));const activity=validateActivityWindow(validateActivity(d)),item=appendActivity(Object.assign({id:Utilities.getUuid(),createdAt:new Date().toISOString()},activity));return out(Object.assign({version:API_VERSION,features:FEATURES,ok:true},item))}catch(e){return out({version:API_VERSION,ok:false,error:{code:e.code||'server_error',message:e.code?e.message:'The request could not be completed',details:e.details||[]}})}finally{if(locked)lock.releaseLock()}}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
