const SCORING=__SCORING_CONFIG__;
const API_VERSION=__API_VERSION__;
const LEGACY_API_VERSION=12;
const FEATURES=['categories-v1','balanced-day-bonus','daily-bounties-v3','bounty-hunter','challenge-window','self-registration-v1','idempotent-activity-v1'];
const TABS={activities:'Activities',settings:'Settings',participants:'Participants',benchmarks:'Benchmarks',receipts:'Activity Receipts',configJournal:'Config Journal'};
const CONFIG_CELL_LIMIT=45000;
const ACTIVITY_HEADERS=['id','name','type','category','points','date','createdAt','hardestGrade','bountyId','bountyTitle','note'];
const PARTICIPANT_HEADERS=['name'];
const GRADES=SCORING.grades,CATEGORIES=Object.keys(SCORING.categories);
const MONTHS={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};
function runtimeProperties(){const script=typeof PropertiesService!=='undefined'&&typeof PropertiesService.getScriptProperties==='function'?PropertiesService.getScriptProperties():null;if(script)return script;const documentProps=typeof PropertiesService!=='undefined'&&typeof PropertiesService.getDocumentProperties==='function'?PropertiesService.getDocumentProperties():null;if(documentProps)return documentProps;apiError('runtime_configuration','Apps Script properties are unavailable')}
function configureSpreadsheet(){const active=SpreadsheetApp.getActive();if(!active||typeof active.getId!=='function')apiError('runtime_configuration','Open the bound Sheet before configuring the web app');runtimeProperties().setProperty('roadToSendSpreadsheetId',active.getId());return active.getId()}
function spreadsheet(){const props=runtimeProperties(),id=props.getProperty('roadToSendSpreadsheetId');if(id&&typeof SpreadsheetApp.openById==='function')return SpreadsheetApp.openById(id);const active=SpreadsheetApp.getActive();if(!active)apiError('runtime_configuration','Run configureSpreadsheet from the bound Sheet before deploying');if(typeof active.getId==='function')props.setProperty('roadToSendSpreadsheetId',active.getId());return active}
function tab(name){const s=spreadsheet();return s.getSheetByName(name)||s.insertSheet(name)}
function normalizeKey(v){return String(v==null?'':v).trim().toLowerCase().replace(/[\s_-]+/g,'')}
function archiveSheet(sheet,label){if(!sheet)return;const stamp=Utilities.formatDate(new Date(),sheetTimeZone(),'yyyyMMdd-HHmmss');sheet.setName(label+' Archive '+stamp)}
function ensureHeaders(sheet,headers){if(sheet.getLastRow()===0)sheet.appendRow(headers);const current=sheet.getRange(1,1,1,Math.max(1,sheet.getLastColumn())).getValues()[0],seen={};current.forEach(x=>seen[normalizeKey(x)]=true);headers.forEach(h=>{if(!seen[normalizeKey(h)]){sheet.getRange(1,sheet.getLastColumn()+1).setValue(h);seen[normalizeKey(h)]=true}})}
// Provisioning (archive, schema stamp, formatSheets) is first-time-only: once a doc is stamped at
// the current schema it is skipped, so every read and write stops paying for formatSheets. The cheap
// ensureHeaders self-heal still runs each call so a hand-edited header row is repaired on next sync.
function hasHeaders(sheet,headers){if(!sheet||sheet.getLastRow()===0)return false;const values=sheet.getRange(1,1,1,Math.max(1,sheet.getLastColumn())).getValues()[0].map(normalizeKey);return headers.every(h=>values.indexOf(normalizeKey(h))>=0)}
function setup(){const book=spreadsheet(),props=runtimeProperties(),schema=props.getProperty('roadToSendSchema'),current=hasHeaders(book.getSheetByName(TABS.activities),ACTIVITY_HEADERS)&&hasHeaders(book.getSheetByName(TABS.settings),['key','value'])&&hasHeaders(book.getSheetByName(TABS.participants),PARTICIPANT_HEADERS),hasExisting=Boolean(book.getSheetByName(TABS.activities)||book.getSheetByName(TABS.benchmarks)||book.getSheetByName(TABS.settings)||book.getSheetByName(TABS.participants)),provisioned=schema==='9'||(!schema&&current);if(!schema&&current)props.setProperty('roadToSendSchema','9');if(!provisioned&&hasExisting){archiveSheet(book.getSheetByName(TABS.activities),'Activities');archiveSheet(book.getSheetByName(TABS.benchmarks),'Benchmarks')}if(!provisioned)props.setProperty('roadToSendSchema','9');const a=tab(TABS.activities),s=tab(TABS.settings),p=tab(TABS.participants),r=tab(TABS.receipts);ensureHeaders(a,ACTIVITY_HEADERS);ensureHeaders(p,PARTICIPANT_HEADERS);ensureHeaders(r,['record']);ensureHeaders(tab(TABS.configJournal),['entry']);if(s.getLastRow()===0)s.appendRow(['key','value']);if(!provisioned)formatSheets(a,s,p)}
function formatSheets(a,s,p){[a,s,p].forEach(x=>{x.setFrozenRows(1);x.getRange(1,1,1,x.getLastColumn()).setFontWeight('bold').setBackground('#e8efe7')});s.getRange('A2').setNote('Required key: challengeStart.');s.getRange('A3').setNote('Required key: tripDate. Inclusive final day.');s.getRange('A4').setNote('Required key: groupGoal.');s.getRange('B2:B3').setNumberFormat('yyyy-mm-dd').setDataValidation(SpreadsheetApp.newDataValidation().requireDate().setAllowInvalid(true).build());s.getRange('B4').setNumberFormat('0').setDataValidation(SpreadsheetApp.newDataValidation().requireNumberBetween(50,10000).setAllowInvalid(false).build());p.getRange(1,1,p.getMaxRows(),Math.max(1,p.getLastColumn())).setNumberFormat('@');const headers=a.getRange(1,1,1,a.getLastColumn()).getValues()[0],dateCol=headers.findIndex(x=>normalizeKey(x)==='date')+1;if(dateCol)a.getRange(1,dateCol,a.getMaxRows(),1).setNumberFormat('yyyy-mm-dd')}
function calendarDate(y,m,d){y=Number(y);m=Number(m);d=Number(d);if(!Number.isInteger(y)||!Number.isInteger(m)||!Number.isInteger(d)||y<1900||y>2200)return null;const x=new Date(Date.UTC(y,m-1,d));if(x.getUTCFullYear()!==y||x.getUTCMonth()+1!==m||x.getUTCDate()!==d)return null;return String(y).padStart(4,'0')+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0')}
function parseDateValue(v){if(v instanceof Date){if(isNaN(v.getTime()))return{error:'is not a valid date'};return{value:Utilities.formatDate(v,sheetTimeZone(),'yyyy-MM-dd')}}const text=String(v==null?'':v).trim();if(!text)return{error:'is required'};let m=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m){const value=calendarDate(m[1],m[2],m[3]);return value?{value}:{error:'must be a real calendar date'}}m=text.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m){const value=calendarDate(m[3],m[1],m[2]);return value?{value}:{error:'must be a real calendar date'}}m=text.match(/^([A-Za-z]+)\s+(\d{1,2})(?:,)?\s+(\d{4})$/);if(m&&MONTHS[m[1].slice(0,3).toLowerCase()]){const value=calendarDate(m[3],MONTHS[m[1].slice(0,3).toLowerCase()],m[2]);return value?{value}:{error:'must be a real calendar date'}}return{error:'must use YYYY-MM-DD, MM/DD/YYYY, or a named month'}}
function parseGoal(v){const text=String(v==null?'':v).trim().replace(/,/g,'');if(!text)return{error:'is required'};const value=Number(text);if(!Number.isFinite(value)||!Number.isInteger(value))return{error:'must be a whole number'};if(value<50||value>10000)return{error:'must be from 50 to 10,000'};return{value}}
function participantRecords(){const values=tab(TABS.participants).getDataRange().getValues();if(!values.length)return[];const headers=values.shift().map(normalizeKey),nameCol=headers.indexOf('name'),seen={};return values.map(r=>({name:String(r[nameCol<0?0:nameCol]||'').trim()})).filter(x=>x.name&&!seen[x.name.toLowerCase()]&&(seen[x.name.toLowerCase()]=true))}
function configError(field,value,reason,cell){return{field,cell:cell||'Settings',value:String(value==null?'':value),reason}}
function readProjectedConfig(){const values=tab(TABS.settings).getDataRange().getValues().slice(1),settings={};values.forEach(r=>{const k=normalizeKey(r[0]);if(k)settings[k]=r[1]});const hasStart=Object.prototype.hasOwnProperty.call(settings,'challengestart'),hasTrip=Object.prototype.hasOwnProperty.call(settings,'tripdate'),hasGoal=Object.prototype.hasOwnProperty.call(settings,'groupgoal');if(!hasStart&&!hasTrip&&!hasGoal)return{config:null,errors:[]};const start=parseDateValue(hasStart?settings.challengestart:''),trip=parseDateValue(hasTrip?settings.tripdate:''),goal=parseGoal(hasGoal?settings.groupgoal:''),crew=participantRecords(),errors=[];if(start.error)errors.push(configError('challengeStart',settings.challengestart,start.error,'Settings!B2'));if(trip.error)errors.push(configError('tripDate',settings.tripdate,trip.error,'Settings!B3'));if(start.value&&trip.value&&start.value>trip.value)errors.push(configError('challengeStart',start.value,'must be on or before the challenge end','Settings!B2'));if(goal.error)errors.push(configError('groupGoal',settings.groupgoal,goal.error,'Settings!B4'));return{config:start.value&&trip.value&&goal.value?{startDate:start.value,tripDate:trip.value,goal:goal.value,crew}:null,errors}}
function normalizeCrew(value){const seen={};return(Array.isArray(value)?value:[]).map(x=>({name:String((typeof x==='string'?x:x&&x.name)||'').trim()})).filter(x=>x.name&&!seen[x.name.toLowerCase()]&&(seen[x.name.toLowerCase()]=true)).map(x=>{if(x.name.length>30)apiError('invalid_config','Participant names must be 30 characters or fewer',[{field:'crew',reason:'name is too long'}]);return x})}
function validateConfig(c){const start=parseDateValue(c&&c.startDate),trip=parseDateValue(c&&c.tripDate),goal=parseGoal(c&&c.goal),errors=[];if(start.error)errors.push(configError('challengeStart',c&&c.startDate,start.error));if(trip.error)errors.push(configError('tripDate',c&&c.tripDate,trip.error));if(start.value&&trip.value&&start.value>trip.value)errors.push(configError('challengeStart',start.value,'must be on or before the challenge end'));if(goal.error)errors.push(configError('groupGoal',c&&c.goal,goal.error));if(errors.length)apiError('invalid_config','Invalid challenge settings',errors);const crew=normalizeCrew(c&&c.crew);if(!crew.length)apiError('invalid_config','Add at least one participant',[{field:'crew',reason:'is required'}]);return{startDate:start.value,tripDate:trip.value,goal:goal.value,crew}}
function readConfig(){const entries=configEntries(),head=entries[entries.length-1];return head?{config:head.result.config,errors:[],revision:head.result.configRevision}:readProjectedConfig()}
function configEntries(){const values=tab(TABS.configJournal).getDataRange().getValues().slice(1),out=[];values.forEach(row=>{try{const entry=JSON.parse(String(row[0]||''));if(entry&&entry.commandId&&entry.payload&&entry.result&&entry.result.config)out.push(entry)}catch{}});return out}
function projectConfig(config){const s=tab(TABS.settings),p=tab(TABS.participants);s.getRange(1,1,Math.max(4,s.getLastRow()),2).clearContent();s.getRange(1,1,4,2).setValues([['key','value'],['challengeStart',config.startDate],['tripDate',config.tripDate],['groupGoal',config.goal]]);p.clearContents();p.getRange(1,1,1,1).setValues([PARTICIPANT_HEADERS]);p.getRange(2,1,config.crew.length,1).setRichTextValues(config.crew.map(x=>[richText(x.name)]));formatSheets(tab(TABS.activities),s,p);return config}
function markConfigProjection(revision){try{runtimeProperties().setProperty('roadToSendConfigProjectionRevision',String(revision))}catch{}}
function projectCommitted(entry){projectConfig(entry.result.config);markConfigProjection(entry.result.configRevision)}
function recoverConfigProjection(){let entries=configEntries(),head=entries[entries.length-1];if(!head)return;let projected='';try{projected=runtimeProperties().getProperty('roadToSendConfigProjectionRevision')||''}catch{}if(projected===String(head.result.configRevision))return;const lock=typeof LockService!=='undefined'&&LockService.getScriptLock?LockService.getScriptLock():null;if(!lock)return;let locked=false;try{lock.waitLock(10000);locked=true;entries=configEntries();head=entries[entries.length-1];if(!head)return;try{projected=runtimeProperties().getProperty('roadToSendConfigProjectionRevision')||''}catch{projected=''}if(projected!==String(head.result.configRevision))projectCommitted(head)}finally{if(locked)lock.releaseLock()}}
function saveConfigCommand(commandId,c){const id=String(commandId||'').trim();if(!id||id.length>100)apiError('invalid_command','A configuration command id from 1 to 100 characters is required',[{field:'configCommandId',reason:'is required'}]);const config=validateConfig(c),payload=JSON.stringify(config),entries=configEntries(),prior=entries.find(x=>x.commandId===id);if(prior){if(prior.payload!==payload)apiError('command_mismatch','That configuration command id was already used for different settings',[{field:'configCommandId',reason:'must identify one immutable command'}]);projectCommitted(entries[entries.length-1]);return prior.result}const result={config,configCommandId:id,configRevision:entries.length+1,receiptId:Utilities.getUuid()},entry={commandId:id,payload,result,committedAt:new Date().toISOString()},serialized=JSON.stringify(entry);if(serialized.length>CONFIG_CELL_LIMIT)apiError('config_too_large','Configuration is too large to save',[{field:'crew',reason:'serialized configuration exceeds '+CONFIG_CELL_LIMIT+' characters'}]);const journal=tab(TABS.configJournal);journal.getRange(journal.getLastRow()+1,1).setValue(serialized);projectCommitted(entry);return result}
function writeConfig(c,commandId){return saveConfigCommand(commandId||Utilities.getUuid(),c).config}
function addParticipant(name){const current=readConfig();if(!current.config)apiError('setup_required','Challenge setup must be completed before profiles can be created');const person=normalizeCrew([{name}])[0];if(!person)apiError('invalid_participant','Enter a name',[{field:'name',reason:'is required'}]);if(current.config.crew.some(x=>x.name.toLowerCase()===person.name.toLowerCase()))apiError('duplicate_participant','That name already exists',[{field:'name',reason:'must be unique'}]);const config=writeConfig(Object.assign({},current.config,{crew:current.config.crew.concat([person])}));return{participant:person,config}}
function normalizeActivityRow(row,headers){const byKey={};headers.forEach((k,i)=>byKey[normalizeKey(k)]=row[i]);const item={};ACTIVITY_HEADERS.forEach(k=>item[k]=byKey[normalizeKey(k)]==null?'':byKey[normalizeKey(k)]);const parsed=parseDateValue(item.date);if(parsed.value)item.date=parsed.value;item.points=Number(item.points)||0;return item}
// Apps Script setValues parses a leading equals sign as a formula. One whole-row rich-text write
// commits every cell together and keeps climber-controlled text literal without apostrophe escaping.
// New point cells are consequently stored as numeric text; normalizeActivityRow restores the numeric
// API type with Number(), and existing rows are never rewritten.
function richText(value){return SpreadsheetApp.newRichTextValue().setText(String(value==null?'':value)).build()}
function appendActivity(item){const a=tab(TABS.activities),headers=a.getRange(1,1,1,a.getLastColumn()).getValues()[0],values=headers.map(h=>{const key=ACTIVITY_HEADERS.find(k=>normalizeKey(k)===normalizeKey(h));return richText(key&&item[key]!=null?item[key]:'')});a.getRange(a.getLastRow()+1,1,1,values.length).setRichTextValues([values]);return item}
function receiptRecords(){const values=tab(TABS.receipts).getDataRange().getValues().slice(1),out=[];values.forEach(row=>{try{const record=JSON.parse(String(row[0]||''));if(record&&record.kind)out.push(record)}catch{}});return out}
function appendReceipt(record){const text=JSON.stringify(record);if(text.length>45000)apiError('invalid_activity','Activity receipt is too large');tab(TABS.receipts).appendRow([text]);return record}
function requestFingerprint(d){const parsed=parseDateValue(d&&d.date);return JSON.stringify({name:String(d&&d.name||'').trim().toLowerCase(),type:String(d&&d.type||''),date:parsed.value||String(d&&d.date||'').trim(),hardestGrade:String(d&&d.hardestGrade||''),note:String(d&&d.note||'').trim(),bountyId:String(d&&d.bountyId||'')})}
function projectActivity(item){const a=tab(TABS.activities),values=a.getDataRange().getValues(),headers=values[0]||ACTIVITY_HEADERS,idCol=headers.findIndex(x=>normalizeKey(x)==='id'),target=headers.map(h=>{const key=ACTIVITY_HEADERS.find(k=>normalizeKey(k)===normalizeKey(h));return item[key]==null?'':item[key]}),at=values.slice(1).findIndex(r=>String(r[idCol])===String(item.id));if(at<0)appendActivity(item);else{const current=values[at+1];if(JSON.stringify(current.slice(0,target.length).map(String))!==JSON.stringify(target.map(String)))a.getRange(at+2,1,1,target.length).setRichTextValues([target.map(richText)])}return item}
function saveActivityCommand(d,version){if(version<15){const activity=validateActivityWindow(validateActivity(d));return appendActivity(Object.assign({id:Utilities.getUuid(),createdAt:new Date().toISOString()},activity))}const mutationId=String(d&&d.mutationId||'').trim();if(!mutationId||mutationId.length>100)apiError('invalid_mutation_id','A mutation ID from 1 to 100 characters is required',[{field:'mutationId',reason:'is required'}]);const fingerprint=requestFingerprint(d),records=receiptRecords(),existing=records.find(x=>x.kind==='activity'&&x.mutationId===mutationId);if(existing){if(existing.fingerprint!==fingerprint)apiError('mutation_mismatch','That mutation ID belongs to a different activity',[{field:'mutationId',reason:'payload differs'}]);if(!records.some(x=>x.kind==='delete'&&String(x.activityId)===String(existing.result.id)))projectActivity(existing.result);return existing.result}const activity=validateActivityWindow(validateActivity(d)),item=Object.assign({id:Utilities.getUuid(),createdAt:new Date().toISOString()},activity);appendReceipt({kind:'activity',mutationId,fingerprint,result:item});projectActivity(item);return item}
function rows(){const values=tab(TABS.activities).getDataRange().getValues(),headers=values.shift()||ACTIVITY_HEADERS,records=receiptRecords(),deleted=new Set(records.filter(x=>x.kind==='delete').map(x=>String(x.activityId))),committed=new Map();records.filter(x=>x.kind==='activity'&&x.result&&!deleted.has(String(x.result.id))).forEach(x=>committed.set(String(x.result.id),x.result));const projected=new Set(),items=values.filter(r=>r.some(c=>c!=='' )).map(r=>normalizeActivityRow(r,headers)).filter(x=>!deleted.has(String(x.id))).map(x=>{const id=String(x.id);projected.add(id);return committed.get(id)||x});committed.forEach((item,id)=>{if(!projected.has(id))items.push(item)});return items}
function apiError(code,message,details){const e=new Error(message);e.code=code;e.details=details||[];throw e}
function canonicalParticipant(name){const text=String(name==null?'':name).trim(),match=participantRecords().find(x=>x.name.toLowerCase()===text.toLowerCase());if(!text||!match)apiError('invalid_activity','Choose a participant from the Participants tab',[{field:'name',reason:'must match a participant'}]);return match}
function bountyById(id){const key=String(id||'');for(let i=0;i<SCORING.bounties.length;i++)if(SCORING.bounties[i].id===key)return SCORING.bounties[i];return null}
function hashText(text){let h=2166136261;const s=String(text);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function dailyBounties(date){const day=String(date||'').slice(0,10),out=[];CATEGORIES.forEach(cat=>{const pool=SCORING.bounties.filter(b=>b.category===cat);if(pool.length)out.push(pool[hashText(day+'|'+cat)%pool.length])});return out}
function validateActivity(d){const participant=canonicalParticipant(d&&d.name),type=String(d&&d.type||''),date=parseDateValue(d&&d.date),hardestGrade=String(d&&d.hardestGrade||''),note=String(d&&d.note||'').trim(),bountyId=String(d&&d.bountyId||''),errors=[];if(['climb','exercise','mobility','bounty'].indexOf(type)<0)errors.push({field:'type',reason:'must be climb, exercise, mobility, or bounty'});if(date.error)errors.push({field:'date',reason:date.error});if(type==='climb'&&hardestGrade&&GRADES.indexOf(hardestGrade)<0)errors.push({field:'hardestGrade',reason:'must be V0 through V17'});if(note.length>120)errors.push({field:'note',reason:'must be 120 characters or fewer'});let bounty=null;if(type==='bounty'){bounty=bountyById(bountyId);if(!bounty)errors.push({field:'bountyId',reason:'must be one of today’s bounties'});else if(date.value&&!dailyBounties(date.value).some(b=>b.id===bounty.id))errors.push({field:'bountyId',reason:'is not available on that date'})}if(errors.length)apiError('invalid_activity','Invalid activity',errors);const category=type==='bounty'?bounty.category:type,points=type==='bounty'?bounty.points:SCORING.categories[type];return{name:participant.name,type,category,points,date:date.value,hardestGrade:type==='climb'?hardestGrade:'',bountyId:type==='bounty'?bounty.id:'',bountyTitle:type==='bounty'?bounty.title:'',note}}
function validateActivityWindow(activity){const c=readConfig().config;if(c&&(activity.date<c.startDate||activity.date>c.tripDate))apiError('outside_challenge_window','Activity date must be from '+c.startDate+' through '+c.tripDate+' (inclusive)',[{field:'date',reason:'is outside the challenge window'}]);return activity}
function deleteActivity(id){const records=receiptRecords(),known=records.some(x=>x.kind==='activity'&&String(x.result&&x.result.id)===id),already=records.some(x=>x.kind==='delete'&&String(x.activityId)===id);if(known&&!already)appendReceipt({kind:'delete',activityId:id,deletedAt:new Date().toISOString()});const a=tab(TABS.activities),values=a.getDataRange().getValues();if(!values.length)return known||already;const headers=values[0],idCol=headers.findIndex(x=>normalizeKey(x)==='id'),rowIndex=values.slice(1).findIndex(r=>String(r[idCol])===id);if(rowIndex<0)return known||already;a.deleteRow(rowIndex+2);return true}
function sheetTimeZone(){return spreadsheet().getSpreadsheetTimeZone()||'UTC'}
function sheetToday(){return Utilities.formatDate(new Date(),sheetTimeZone(),'yyyy-MM-dd')}
function negotiatedVersion(value){const requested=Number(value);return Number.isInteger(requested)&&requested>=13&&requested<=API_VERSION?requested:LEGACY_API_VERSION}
function responseFeatures(version){const base=FEATURES.filter(x=>x!=='idempotent-activity-v1');return base.concat(version>=13?['protocol-negotiation-v1']:[],version>=14?['literal-text-v1']:[],version>=15?['idempotent-activity-v1']:[],version>=16?['config-journal-v1']:[])}
function doGet(e){const version=negotiatedVersion(e&&e.parameter&&e.parameter.protocolVersion);try{setup();try{recoverConfigProjection()}catch{}const c=readConfig();return out({version,features:responseFeatures(version),activities:rows(),config:c.config,configErrors:c.errors,configRevision:c.revision||0,serverDate:sheetToday(),timeZone:sheetTimeZone(),fetchedAt:new Date().toISOString()})}catch(error){return out({version,features:responseFeatures(version),ok:false,error:{code:error.code||'server_error',message:error.code?error.message:'The request could not be completed',details:error.details||[]}})}}
function doPost(e){let lock,locked=false,d,version=LEGACY_API_VERSION;try{try{d=JSON.parse(e&&e.postData&&e.postData.contents||'')}catch(parseError){apiError('invalid_json','Request body must be valid JSON')}if(!d||typeof d!=='object'||Array.isArray(d))apiError('invalid_request','Request body must be a JSON object');version=negotiatedVersion(d.protocolVersion);lock=LockService.getScriptLock();if(!lock)apiError('runtime_lock','Apps Script locking is unavailable');lock.waitLock(10000);locked=true;setup();if(d.action==='saveConfig'){const saved=version>=16?saveConfigCommand(d.configCommandId,d.config||{}):saveConfigCommand(Utilities.getUuid(),d.config||{});return out(Object.assign({version,features:responseFeatures(version),ok:true,configErrors:[]},saved))}if(d.action==='addParticipant'){const added=addParticipant(d.name);return out({version,features:responseFeatures(version),ok:true,participant:added.participant,config:added.config,configErrors:[]})}if(d.action==='delete'){const id=String(d.id==null?'':d.id).trim();if(!id)apiError('invalid_delete','An activity id is required',[{field:'id',reason:'is required'}]);return deleteActivity(id)?out({version,features:responseFeatures(version),ok:true,deleted:id}):out({version,features:responseFeatures(version),ok:false,error:{code:'not_found',message:'Activity not found'}})}if(d.action)apiError('unknown_action','Unsupported action: '+String(d.action));const item=saveActivityCommand(d,version);return out(Object.assign({version,features:responseFeatures(version),ok:true},item))}catch(e){return out({version,features:responseFeatures(version),ok:false,error:{code:e.code||'server_error',message:e.code?e.message:'The request could not be completed',details:e.details||[]}})}finally{if(locked)lock.releaseLock()}}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
